  CREATE TABLE "CRM_T_DEPOSIT_APPLY" 
  ("C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_AMOUNT" VARCHAR2(20 BYTE), 
  "C_APPLY_TYPE" VARCHAR2(32 BYTE), 
  "C_NATURE" VARCHAR2(32 BYTE), 
  "C_PAYMENT_COMPANY" VARCHAR2(32 BYTE), 
  "C_OPPORTUNITY" VARCHAR2(32 BYTE),
  "C_APPLY_CODE" VARCHAR2(32 BYTE),
  "C_PAYMENT_BANK" VARCHAR2(32 BYTE),
  "C_QUOTATION" VARCHAR2(32 BYTE),
  "C_APPLY_DATE" VARCHAR2(32 BYTE), 
  "C_PAYMENT_ACCOUNT" VARCHAR2(32 BYTE), 
  "C_CONTRACT" VARCHAR2(32 BYTE), 
  "DT_PAYMENT_DATE_RETURN" DATE, 
  "C_CURRENCY" VARCHAR2(32 BYTE),
  "C_STATUS" VARCHAR2(32 BYTE), 
  "DT_PAYMENT_DATE" DATE, 
  "C_COMMENT" VARCHAR2(200 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_DEPOSIT_APPLY" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_PID" IS 'ID';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."APPLIER_ID" IS '申请人';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."APPLIER_POS_ID" IS '申请人岗位';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."APPLIER_ORG_ID" IS '申请人组织';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_AMOUNT" IS '金额';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_APPLY_TYPE" IS '申请类型';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_NATURE" IS '资金性质';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_PAYMENT_COMPANY" IS '收款单位名称';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_OPPORTUNITY" IS '商机名称';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_APPLY_CODE" IS '申请编号';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_PAYMENT_BANK" IS '收款单位银行名称';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_QUOTATION" IS '报价单';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_APPLY_DATE" IS '申请时间';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_PAYMENT_ACCOUNT" IS '收款单位银行账号';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_CONTRACT" IS '合同';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."DT_PAYMENT_DATE_RETURN" IS '拟回款日期';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_CURRENCY" IS '币种';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_STATUS" IS '状态';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."DT_PAYMENT_DATE" IS '拟付款日期';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_COMMENT" IS '备注';

COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_CREATED_BY_ID" IS '创建人';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."DT_CREATED_AT" IS '创建时间';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_CREATED_POS_ID" IS '创建人岗位';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_CREATED_ORG_ID" IS '创建人组织';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."C_UPDATED_BY_ID" IS '更新者';
COMMENT ON COLUMN "CRM_T_DEPOSIT_APPLY"."DT_UPDATED_AT" IS '更新时间';


