CREATE TABLE "KCRM"."CRM_T_BIZ_SALE_IN_TEAM" 
   (	"N_PID" NUMBER NOT NULL ENABLE, 
	"C_SALE_CENTER" VARCHAR2(30), 
	"C_SALE_DEPT" VARCHAR2(30), 
	"C_PERSON_NAME" VARCHAR2(10), 
	"N_IS_RESPONSIBLE" NUMBER, 
	"C_BIZ_ENTITY" VARCHAR2(30), 
	"C_ROLE" VARCHAR2(10), 
	"C_AUTHORITY" VARCHAR2(10), 
	 CONSTRAINT "BIZ_SALE_IN_TEAM_PK" PRIMARY KEY ("N_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."BIZ_SALE_IN_TEAM_PK" ON "KCRM"."CRM_T_BIZ_SALE_IN_TEAM" ("N_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_BIZ_SALE_IN_TEAM" ADD CONSTRAINT "BIZ_SALE_IN_TEAM_PK" PRIMARY KEY ("N_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_BIZ_SALE_IN_TEAM" MODIFY ("N_PID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."N_PID" IS 'primary key';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."C_SALE_CENTER" IS '销售中心';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."C_SALE_DEPT" IS '销售部门';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."C_PERSON_NAME" IS '人员姓名';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."N_IS_RESPONSIBLE" IS '责任人';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."C_BIZ_ENTITY" IS '业务实体';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."C_ROLE" IS '角色';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"."C_AUTHORITY" IS '权限';
 
   COMMENT ON TABLE "KCRM"."CRM_T_BIZ_SALE_IN_TEAM"  IS '商机销售内部团队表';