CREATE TABLE CRM_T_BUSINESS_OPPORTUNITY 
   (	
	    C_PID VARCHAR2(32) NOT NULL ENABLE, 
		C_SALE_STAGE VARCHAR2(32), 
		C_BUSINESS_PROCESS VARCHAR2(32), 
		C_ENTERPRISE VARCHAR2(32), 
		C_NUMBER VARCHAR2(32), 
		C_STATUS VARCHAR2(33), 
		C_SALER_ID VARCHAR2(32),
		C_SALER_NAME VARCHAR2(32), 
		C_CREATER VARCHAR2(32), 
		C_CONFLICT_STATUS VARCHAR2(32), 
		C_SALER_PHONE VARCHAR2(20), 
		DT_CREATE_TIME TIMESTAMP(6), 
		C_CONFLICT_NUMBER VARCHAR2(32), 
		C_CLIENT_ID VARCHAR2(32), 
		C_CLIENT_NAME VARCHAR2(80),
		C_INDUSTRY VARCHAR2(80),
		C_BID_UNIT VARCHAR2(80),
		C_KEY_CONTACT VARCHAR2(80),
		C_CONTACT_DEPT VARCHAR2(80),
		C_CONTACT_PHONE VARCHAR2(20),
		C_OPPORTUNITY_NAME VARCHAR2(80), 
		C_ADDRESS VARCHAR2(80), 
		DT_PLAN_FIN_DATE TIMESTAMP(6), 
		C_SALE_METHOD VARCHAR2(32), 
		N_SUCCESS_RATE NUMBER(32,4), 
		C_PROJECT_SITUATION VARCHAR2(300), 
		C_PROJECT_PROGRESS VARCHAR2(300), 
		N_IS_INTEGREATED NUMBER, 
		C_BIZ_OPP_ADDRESS VARCHAR2(32), 
		C_SOURCE VARCHAR2(10), 
		C_CURRENCY VARCHAR2(32), 
		N_ESTIMATED_AMOUNT NUMBER(32,4),
		DT_UPDATE_TIME TIMESTAMP(6),
		C_COMPETITIVE_BRANDS VARCHAR2(32),
		C_PROJECT_TYPE VARCHAR2(30)
	)
 tablespace TS_CRM
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_PID IS 'primary key';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_SALE_STAGE IS '销售阶段';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_BUSINESS_PROCESS IS '业务流程';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_ENTERPRISE IS '报备单位';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_NUMBER IS '商机编号';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_STATUS IS '状态';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_SALER_ID IS '销售ID';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_SALER_NAME IS '销售员';
      
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CREATER IS '报备人';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CONFLICT_STATUS IS '冲突状态';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_SALER_PHONE IS '销售员电话';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.DT_CREATE_TIME IS '创建日期';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CONFLICT_NUMBER IS '冲突管理单';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CLIENT_ID IS '客户ID';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CLIENT_NAME IS '客户名称';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_INDUSTRY IS '行业';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_KEY_CONTACT IS '主要联系人';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CONTACT_DEPT IS '联系人部门';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CONTACT_PHONE IS '联系人电话';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_BID_UNIT IS '招标单位';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_OPPORTUNITY_NAME IS '商机名称';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_ADDRESS IS '详细地址';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.DT_PLAN_FIN_DATE IS '预计成交时间';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_SALE_METHOD IS '销售方法';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.N_SUCCESS_RATE IS '成功率';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_PROJECT_SITUATION IS '项目概况';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_PROJECT_PROGRESS IS '项目推动情况';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.N_IS_INTEGREATED IS '是否集成包';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_BIZ_OPP_ADDRESS IS '商机所在地';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_SOURCE IS '来源';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_CURRENCY IS '币种';
 
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.N_ESTIMATED_AMOUNT IS '预计金额';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.DT_UPDATE_TIME IS '更新时间';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_COMPETITIVE_BRANDS IS '竞争品牌';
   
   COMMENT ON COLUMN CRM_T_BUSINESS_OPPORTUNITY.C_PROJECT_TYPE IS '立项类型';
   
   COMMENT ON TABLE  CRM_T_BUSINESS_OPPORTUNITY  IS '商机信息表';
   
-- Create/Recreate indexes  

-- Create/Recreate primary, unique and foreign key constraints 
alter table CRM_T_BUSINESS_OPPORTUNITY
  add constraint PT_M_T_BUSINESS_OPPORTUNITY primary key (C_PID)
  using index 
  tablespace TS_CRM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );