CREATE TABLE "CRM_T_BIZ_SPE_PRICE_APP" 
   ("C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_APPLICANT" VARCHAR2(32), 
	"C_APPLY_NUMBER" VARCHAR2(32), 
	"C_APPLY_STATUS" VARCHAR2(32), 
	"C_APPLY_UNIT" VARCHAR2(32), 
	"C_DISCOUNT" VARCHAR2(32), 
	"DT_APPLY_DATE" DATE, 
	"C_TOTAL_PRICE" VARCHAR2(32),
	"C_DISCOUNT_TOTAL_PRICE" VARCHAR2(32),
	"DT_VALID_DATE" DATE, 
	"C_EXPLANATION" VARCHAR2(300), 
	 CONSTRAINT "SPE_PRICE_APP" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_PID" IS 'primary key';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_APPLICANT" IS '申请人';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_APPLY_NUMBER" IS '申请编号';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_APPLY_STATUS" IS '申请状态';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_APPLY_UNIT" IS '申请单位';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_DISCOUNT" IS '折扣';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."DT_APPLY_DATE" IS '申请日期';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_TOTAL_PRICE" IS '价目表总金额';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_DISCOUNT_TOTAL_PRICE" IS '折扣后总金额';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."DT_VALID_DATE" IS '特价有效期至';
 
   COMMENT ON COLUMN "CRM_T_BIZ_SPE_PRICE_APP"."C_EXPLANATION" IS '说明';
 
   COMMENT ON TABLE "CRM_T_BIZ_SPE_PRICE_APP"  IS '商机特价申请表';