CREATE TABLE "CRM_T_BID" 
   ("C_PID" VARCHAR2(32) NOT NULL ENABLE,
	"C_AUTHORIZATION_NAME" VARCHAR2(80), 
	"C_AUTHORIZATION_DISC" VARCHAR2(80),
	"C_BID_ENTERPRISE" VARCHAR2(80), 
	"C_BID_NUMBER" VARCHAR2(32), 
	"C_BUSINESS_OPP_ID" VARCHAR2(32), 
	"C_BUSINESS_OPP_NAME" VARCHAR2(80), 
	"C_BID_AUTH_NUMBER" VARCHAR2(32), 
	"C_CREATOR" VARCHAR2(32), 
	"DT_CREATE_DATE" DATE, 
	"C_AGENCY" VARCHAR2(80), 
	"DT_BID_START_DATE" DATE, 
	"C_STATUS" VARCHAR2(32), 
	"C_TERMINAL_CLIENT" VARCHAR2(80), 
	"C_PROJECT_ADDRESS" VARCHAR2(80), 
	"C_INDUSTRY" VARCHAR2(32), 
	"C_IS_INTEGRATED" VARCHAR2(80), 
	"C_IS_CROSS_DISTRICT" VARCHAR2(80), 
	"C_CROSS_DEPARTMENT" VARCHAR2(80), 
	"C_INVOLVE_INDUSTRY" VARCHAR2(80), 
	"C_PERSON_IN_CHARGE" VARCHAR2(10), 
	"C_CONNECT_METHOD" VARCHAR2(32), 
	"C_RESPONSIBLE_DEP" VARCHAR2(80), 
	"C_AUTH_NOBID_DISC" VARCHAR2(1000), 
	"DT_START_TIME" DATE, 
	"DT_END_TIME" DATE, 
	"C_REMARK" VARCHAR2(1000), 
	"C_BID_RESULT" VARCHAR2(32), 
	"C_FEEDBACK" VARCHAR2(32), 
	"C_BID_REMARK" VARCHAR2(80), 
	 CONSTRAINT "CRM_T_BID_ID" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

 
   COMMENT ON COLUMN "CRM_T_BID"."C_PID" IS 'primary key';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_AUTHORIZATION_NAME" IS '授权名称';
   
   COMMENT ON COLUMN "CRM_T_BID"."C_AUTHORIZATION_DISC" IS '授权产品描述';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_BID_ENTERPRISE" IS '招标单位';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_BID_NUMBER" IS '招标编号';
   
   COMMENT ON COLUMN "CRM_T_BID"."C_BUSINESS_OPP_ID" IS '商机编号';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_BUSINESS_OPP_NAME" IS '商机名称';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_BID_AUTH_NUMBER" IS '招标授权编号';
   
   COMMENT ON COLUMN "CRM_T_BID"."C_CREATOR" IS '创建用户'; 
 
   COMMENT ON COLUMN "CRM_T_BID"."DT_CREATE_DATE" IS '创建日期';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_AGENCY" IS '代理商';
 
   COMMENT ON COLUMN "CRM_T_BID"."DT_BID_START_DATE" IS '开标时间';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_STATUS" IS '状态';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_TERMINAL_CLIENT" IS '终端客户';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_PROJECT_ADDRESS" IS '项目所在地';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_INDUSTRY" IS '行业';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_IS_INTEGRATED" IS '是否集成';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_IS_CROSS_DISTRICT" IS '是否跨区';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_CROSS_DEPARTMENT" IS '跨区部门';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_INVOLVE_INDUSTRY" IS '涉及行业部';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_PERSON_IN_CHARGE" IS '负责人';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_CONNECT_METHOD" IS '联系方式';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_RESPONSIBLE_DEP" IS '负责部门';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_AUTH_NOBID_DISC" IS '已授权未投标说明';
 
   COMMENT ON COLUMN "CRM_T_BID"."DT_START_TIME" IS '开始时间';
 
   COMMENT ON COLUMN "CRM_T_BID"."DT_END_TIME" IS '结束时间';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_REMARK" IS '备注';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_BID_RESULT" IS '投标结果';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_FEEDBACK" IS '反馈情况';
 
   COMMENT ON COLUMN "CRM_T_BID"."C_BID_REMARK" IS '投标结果备注';
 
   COMMENT ON TABLE "CRM_T_BID"  IS '项目投标授权表';