CREATE TABLE CRM_T_BIZ_WEEKLY_REPORT
   (	
    C_PID  VARCHAR2(32), 
	C_FK_WEEKLY_ID  VARCHAR2(32), 
	N_CLIENT_NAME VARCHAR2(30), 
	N_IS_NEW_CLIENT NUMBER, 
	N_IS_OLD_CLIENT NUMBER, 
	N_BACKUP_MACHINE NUMBER, 
	N_HOME_INVERTER NUMBER, 
	N_POWER_FREQUENCY_MACHINE NUMBER, 
	N_BATTERY NUMBER, 
	N_HIGH_FREQUENCY NUMBER, 
	N_IDU_IDM NUMBER, 
	N_SINGLE_PHASE_INVERTER NUMBER, 
	N_THREE_PHASE_INVERTER NUMBER, 
	N_CENTRAL_INVERTER NUMBER, 
	N_MW_HOUSE NUMBER, 
	N_STORED_ENERGY NUMBER, 
	N_AIR_CONDITION NUMBER, 
	N_NOT_SHIPPED_THIS_MONTH NUMBER(32,4), 
	N_NOT_SHIPPED_NEXT_MONTH NUMBER(32,4), 
	N_NOT_SHIPPED_N_N_MONTH NUMBER(32,4), 
	N_SHIPPED_THIS_MONTH NUMBER(32,4),
	N_SHIPPED_NEXT_MONTH NUMBER(32,4), 
	N_SHIPPED_N_N_MONTH NUMBER(32,4), 
	N_CONTACT_METHOD_MAIL NUMBER, 
	N_CONTACT_METHOD_PHONE NUMBER, 
	N_CONTACT_METHOD_VISIT NUMBER, 
	N_CONTACT_COME_VISIT NUMBER, 
	C_PROBLEM_METHOD VARCHAR2(300), 
	C_REMARK VARCHAR2(300)
  )
  tablespace TS_CRM
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
  
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.C_PID IS 'primary key';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.C_FK_WEEKLY_ID IS '周报题头主表ID';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_CLIENT_NAME IS '客户名称';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_IS_NEW_CLIENT IS '客户类别 新客户';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_IS_OLD_CLIENT IS '客户类别 老客户';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_BACKUP_MACHINE IS '后备机';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_HOME_INVERTER IS '家用逆变器';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_POWER_FREQUENCY_MACHINE IS '工频机';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_BATTERY IS '电池';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_HIGH_FREQUENCY IS '>20K高频';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_IDU_IDM IS 'IDU/IDM';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_SINGLE_PHASE_INVERTER IS '单相光伏逆变器';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_THREE_PHASE_INVERTER IS '三相光伏逆变器';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_CENTRAL_INVERTER IS '集中型逆变器';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_MW_HOUSE IS 'MW房';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_STORED_ENERGY IS '储能';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_AIR_CONDITION IS '空调';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_NOT_SHIPPED_THIS_MONTH IS '未出货订单金额（USD） 本月';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_NOT_SHIPPED_NEXT_MONTH IS '未出货订单金额（USD） 下月';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_NOT_SHIPPED_N_N_MONTH IS '未出货订单金额（USD） 下下月';
   
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_SHIPPED_THIS_MONTH IS '出货订单金额（USD） 本月';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_SHIPPED_NEXT_MONTH IS '出货订单金额（USD） 下月';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_SHIPPED_N_N_MONTH IS '出货订单金额（USD） 下下月';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_CONTACT_METHOD_MAIL IS '客户沟通维护方式 邮件';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_CONTACT_METHOD_PHONE IS '客户沟通维护方式 电话';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_CONTACT_METHOD_VISIT IS '客户沟通维护方式 拜访';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.N_CONTACT_COME_VISIT IS '客户沟通维护方式 来访';
 
   COMMENT ON COLUMN CRM_T_BIZ_WEEKLY_REPORT.C_PROBLEM_METHOD IS '存在问题和处理方式';
 
   COMMENT ON COLUMN  CRM_T_BIZ_WEEKLY_REPORT.C_REMARK IS '备注';
 
   COMMENT ON TABLE  CRM_T_BIZ_WEEKLY_REPORT  IS '商机国际业绩周报进展汇报表';
   
-- Create/Recreate indexes  

-- Create/Recreate primary, unique and foreign key constraints 
alter table CRM_T_BIZ_WEEKLY_REPORT
  add constraint CRM_T_BIZ_WEEKLY_REPORT primary key (C_PID)
  using index 
  tablespace TS_CRM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
