CREATE TABLE CRM_T_BIZ_SPE_PRICE_APP_LINE 
   (
     C_PID VARCHAR2(32) NOT NULL ENABLE, 
     C_SPE_PRICE_ID VARCHAR2(32),
     C_PRODUCT_MODEL VARCHAR2(32), 
     C_MATERIAL_NUMBER VARCHAR2(32),
     C_MATERIAL_NAME VARCHAR2(80),
     N_CATALOGE_PRICE NUMBER(32,4),
     N_COUNT NUMBER,
     N_APPLY_COUNT NUMBER,
     N_APPLY_DISCOUNT NUMBER(32,4),
     N_APPROVED_DISCOUNT NUMBER(32,4),
     N_DISCOUNT_PRICE NUMBER(32,4),
     N_DISCOUNT_TOTAL NUMBER(32,4),
     C_REMARK VARCHAR2(80)
  )

tablespace TS_CRM
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (  
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.C_PID IS 'primary key';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.C_SPE_PRICE_ID IS '特价表主键';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.C_PRODUCT_MODEL IS '产品型号';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.C_MATERIAL_NUMBER IS '料号';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.C_MATERIAL_NAME IS '物料名称';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_CATALOGE_PRICE IS '目录价格';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_COUNT IS '数量';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_APPLY_COUNT IS '申请数量';
   
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_APPLY_DISCOUNT IS '申请折扣';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_APPROVED_DISCOUNT IS '批复折扣';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_DISCOUNT_PRICE IS '折扣价';
   
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.N_DISCOUNT_TOTAL IS '折扣总额';
 
   COMMENT ON COLUMN CRM_T_BIZ_SPE_PRICE_APP_LINE.C_REMARK IS '备注';
   
   COMMENT ON TABLE CRM_T_BIZ_SPE_PRICE_APP_LINE  IS '特价明细表';
   
-- Create/Recreate indexes  

-- Create/Recreate primary, unique and foreign key constraints 
alter table CRM_T_BIZ_SPE_PRICE_APP_LINE
  add constraint PK_CRM_BIZ_SPE_PRICE_APP_LINE primary key (C_PID)
  using index 
  tablespace TS_CRM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );