
  CREATE TABLE "CRM_T_PROTOTYPE_APPLY" 
   ("C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
    "C_SYSTEM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
	"C_VCODE" VARCHAR2(32 BYTE), 
	"C_PRODUCT_MODEL" VARCHAR2(32 BYTE), 
	"C_MATERIAL_NUMBER" VARCHAR2(32 BYTE), 
	"C_PRODUCT_DESC" VARCHAR2(32 BYTE), 
	"C_APPLY_COUNT" VARCHAR2(32 BYTE), 
	"C_TYPE" VARCHAR2(32 BYTE), 
	"C_REMARK" VARCHAR2(80 BYTE), 
	"C_IS_STANDARD" VARCHAR2(32 BYTE),  
	 CONSTRAINT "PROTOTYPE_APPLY_PK" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_PID" IS 'primary key';
   
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_SYSTEM_PID" IS '系统ID';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_VCODE" IS 'VCode';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_PRODUCT_MODEL" IS '产品型号';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_MATERIAL_NUMBER" IS '产品料号';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_PRODUCT_DESC" IS '产品描述';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_APPLY_COUNT" IS '申请数量';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_TYPE" IS '类型';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_REMARK" IS '备注';
 
   COMMENT ON COLUMN "CRM_T_PROTOTYPE_APPLY"."C_IS_STANDARD" IS '标准产品';
 
   COMMENT ON TABLE "CRM_T_PROTOTYPE_APPLY"  IS '商机样机申请_样机列表';
 
