CREATE TABLE CRM_T_BIZOPP_PRODUCTS_DETAIL 
   (	
  C_PID VARCHAR2(32) NOT NULL ENABLE, 
	C_BIZOPP_ID VARCHAR2(32), 
	C_PRODUCT_ID VARCHAR2(32), 
	C_PRODUCT_NAME VARCHAR2(50), 
	C_PRODUCT_TYPE VARCHAR2(30), 
	C_PRODUCT_MODEL VARCHAR2(30), 
	N_PLAN_COUNT NUMBER, 
	N_PLAN_PRICE NUMBER(32,4), 
	N_PLAN_TOTAL NUMBER(32,4),
	C_REMARK VARCHAR2(100), 
	N_IS_STANDARD NUMBER
   ) 
 tablespace TS_CRM
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_PID IS 'primary key';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_BIZOPP_ID IS '商机ID';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_PRODUCT_ID IS '产品ID';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_PRODUCT_NAME IS '产品名称';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_PRODUCT_TYPE IS '产品类别';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_PRODUCT_MODEL IS '产品型号';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.N_PLAN_COUNT IS '预计数量';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.N_PLAN_PRICE IS '预计价格';
   
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.N_PLAN_TOTAL IS '预计金额';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.C_REMARK IS '备注';
 
   COMMENT ON COLUMN CRM_T_BIZOPP_PRODUCTS_DETAIL.N_IS_STANDARD IS '是否标准';
 
   COMMENT ON TABLE CRM_T_BIZOPP_PRODUCTS_DETAIL  IS '商机_项目配置明细表';
   
-- Create/Recreate indexes  

-- Create/Recreate primary, unique and foreign key constraints 
alter table CRM_T_BIZOPP_PRODUCTS_DETAIL
  add constraint PK_M__BIZOPP_PRODUCTS_DETAIL primary key (C_PID)
  using index 
  tablespace TS_CRM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );