CREATE TABLE "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY" 
   (	"N_PID" NUMBER NOT NULL ENABLE, 
	"C_SALESMAN" VARCHAR2(20), 
	"C_DEPARTMENT" VARCHAR2(20), 
	"DT_YEAR" DATE, 
	"DT_CREATE_DATE" DATE, 
	"N_WEEKS" NUMBER, 
	"C_STATUS" VARCHAR2(10), 
	"N_NEW_CLIENT" NUMBER, 
	"N_PLAN_DEAL" NUMBER, 
	"N_CLIENT_COUNT" NUMBER, 
	"N_PLACE_ORDER_C" NUMBER, 
	 CONSTRAINT "BIZ_PERFORMANCE_WEEKLY_PK" PRIMARY KEY ("N_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."BIZ_PERFORMANCE_WEEKLY_PK" ON "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY" ("N_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY" ADD CONSTRAINT "BIZ_PERFORMANCE_WEEKLY_PK" PRIMARY KEY ("N_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY" MODIFY ("N_PID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."N_PID" IS 'primary key';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."C_SALESMAN" IS '销售人员';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."C_DEPARTMENT" IS '所属部门';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."DT_YEAR" IS '年度';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."DT_CREATE_DATE" IS '创建日期';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."N_WEEKS" IS '周数';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."C_STATUS" IS '状态';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."N_NEW_CLIENT" IS '本月新联系（个）';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."N_PLAN_DEAL" IS '预计成交（个）';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."N_CLIENT_COUNT" IS '客户数量(个)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"."N_PLACE_ORDER_C" IS '本周下单客户（个）';
 
   COMMENT ON TABLE "KCRM"."CRM_T_BIZ_PERFORMANCE_WEEKLY"  IS '商机国际业务周报';