CREATE TABLE "KCRM"."CRM_T_BIZ_UPDATE" 
   (	"N_PID" NUMBER NOT NULL ENABLE, 
	"C_SALE_STAGE" VARCHAR2(32), 
	"N_CLIENT_ID" NUMBER, 
	"C_OPPORTUNITY_NAME" VARCHAR2(80), 
	"C_ADDRESS" VARCHAR2(80), 
	"DT_PLAN_FIN_DATE" DATE, 
	"N_SUCCESS_RATE" NUMBER, 
	"C_PROJECT_PROGRESS" VARCHAR2(300), 
	"C_BIZ_OPP_ADDRESS" VARCHAR2(30), 
	"C_BID_UNIT" VARCHAR2(80), 
	"N_VERSION" NUMBER, 
	 CONSTRAINT "N_PID_CRM_T_BIZ_UPDATE" PRIMARY KEY ("N_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."N_PID_CRM_T_BIZ_UPDATE" ON "KCRM"."CRM_T_BIZ_UPDATE" ("N_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_BIZ_UPDATE" ADD CONSTRAINT "N_PID_CRM_T_BIZ_UPDATE" PRIMARY KEY ("N_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_BIZ_UPDATE" MODIFY ("N_PID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."N_PID" IS 'primary key';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."C_SALE_STAGE" IS '销售阶段';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."N_CLIENT_ID" IS '终端用户ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."C_OPPORTUNITY_NAME" IS '商机名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."C_ADDRESS" IS '详细地址';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."DT_PLAN_FIN_DATE" IS '预计成交时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."N_SUCCESS_RATE" IS '成功率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."C_PROJECT_PROGRESS" IS '项目推动情况';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."C_BIZ_OPP_ADDRESS" IS '商机所在地';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."C_BID_UNIT" IS '招标单位';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_BIZ_UPDATE"."N_VERSION" IS '版本号';
 
   COMMENT ON TABLE "KCRM"."CRM_T_BIZ_UPDATE"  IS '商机信息更新记录表';