CREATE TABLE CRM_T_BIZ_SUPPORT_APPLY
   (	
      C_PID VARCHAR2(32), 
      C_APPLICANT_ID VARCHAR2(32),
      C_APPLICANT VARCHAR2(32), 
      C_CLIENT_ID VARCHAR2(32),
      C_CLIENT_NAME VARCHAR2(300), 
      C_NUMBER VARCHAR2(32), 
      C_APPLY_ENTERPRISE VARCHAR2(30), 
      C_BIZ_OPP_ID VARCHAR2(32), 
      C_BIZ_OPP_NAME VARCHAR2(200), 
      DT_CREATE_DATE DATE, 
      C_DEPARTMENT VARCHAR2(32), 
      C_BIZ_OPP_PROGRESS VARCHAR2(100), 
      C_STATUS VARCHAR2(10), 
      N_REPORT_PRICE NUMBER(32,4), 
      C_COMPETITOR VARCHAR2(80), 
      N_IS_1 NUMBER, 
      N_IS_2 NUMBER, 
      N_IS_3 NUMBER, 
      N_IS_4 NUMBER, 
      N_IS_5 NUMBER, 
      N_IS_6 NUMBER, 
      N_IS_7 NUMBER, 
      N_IS_8 NUMBER, 
      N_IS_9 NUMBER, 
      N_IS_10 NUMBER, 
      N_IS_11 NUMBER
  )
 tablespace TS_CRM
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
  
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_PID IS 'primary key';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_APPLICANT_ID IS '申请人ID';
   
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_APPLICANT IS '申请人';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_CLIENT_ID IS '客户ID';
   
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_CLIENT_NAME IS '客户名称';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_NUMBER IS '编号';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_APPLY_ENTERPRISE IS '申请单位';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_BIZ_OPP_ID IS '商机ID';
   
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_BIZ_OPP_NAME IS '商机名称';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.DT_CREATE_DATE IS '创建日期';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_DEPARTMENT IS '部门';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_BIZ_OPP_PROGRESS IS '商机进度';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_STATUS IS '状态';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_REPORT_PRICE IS '报备金额';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.C_COMPETITOR IS '竞争对手';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_1 IS '完善工程界面内容';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_2 IS '现场交流（方案未定）';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_3 IS '现场布置图制作（需上传现场图纸）';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_4 IS '配电图制作';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_5 IS '现场交流（已有方案）';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_6 IS '现场3D图制作（需上传现场图纸）';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_7 IS '方案制作';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_8 IS '设标文档提供';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_9 IS '现场CFD热流模拟（需上传现场图纸）';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_10 IS '投标文件制作';
 
   COMMENT ON COLUMN CRM_T_BIZ_SUPPORT_APPLY.N_IS_11 IS '技术应答文件制作';
 
   COMMENT ON TABLE CRM_T_BIZ_SUPPORT_APPLY  IS '商机技术支持申请表';
   
   -- Create/Recreate indexes  

-- Create/Recreate primary, unique and foreign key constraints 
alter table CRM_T_BIZ_SUPPORT_APPLY
  add constraint PK_M_T_BIZ_SUPPORT_APPLY primary key (C_PID)
  using index 
  tablespace TS_CRM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );