  CREATE TABLE "CRM_T_DOC" 
   (	"C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_DOC_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"C_DOC_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"C_APPLY_PERSON" VARCHAR2(20 BYTE), 
	"DT_APPLY_DATE" DATE, 
	"C_APPLY_STATUS" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"C_UPLOAD_PERSON" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DT_UPLOAD_DATE" DATE NOT NULL ENABLE, 
	"C_ACCESS_GROUP" VARCHAR2(30 BYTE), 
	"C_PRO_ID" VARCHAR2(32 BYTE), 
	"C_PRO_CODE" VARCHAR2(32 BYTE), 
	"C_DOC_URL" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PK_CRM_T_DOC_ID" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 

   COMMENT ON COLUMN "CRM_T_DOC"."C_PID" IS '文档ID';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_DOC_NAME" IS '文档名称';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_DOC_DESC" IS '文档说明';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_APPLY_PERSON" IS '申请人';
 
   COMMENT ON COLUMN "CRM_T_DOC"."DT_APPLY_DATE" IS '申请时间';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_APPLY_STATUS" IS '申请状态';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_UPLOAD_PERSON" IS '上传人';
 
   COMMENT ON COLUMN "CRM_T_DOC"."DT_UPLOAD_DATE" IS '上传时间';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_ACCESS_GROUP" IS '访问组';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_PRO_ID" IS '业务ID';

   COMMENT ON COLUMN "CRM_T_DOC"."C_PRO_CODE" IS '业务CODE';
 
   COMMENT ON COLUMN "CRM_T_DOC"."C_DOC_URL" IS '文档地址';
 
   COMMENT ON TABLE "CRM_T_DOC"  IS '附件信息';
 
