--客户信息(销售团队-内部团队)

CREATE TABLE "CRM_T_SALES_TEAM_IN" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_SYSTEM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_SYSTEM_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_MARK_CENTER" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_MARK_DEPART" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  "C_MARK_NAME" VARCHAR2(100 BYTE),
  "C_MARK_RESPON" VARCHAR2(100 BYTE), 
  "C_MARK_OPERATE_UNIT" VARCHAR2(100 BYTE),
  "C_MARK_ROLE" VARCHAR2(100 BYTE),
  "C_MARK_AUTH" VARCHAR2(100 BYTE),
  "C_MARK_VALID_FROM" VARCHAR2(100 BYTE),
  "C_MARK_VALID_TO" VARCHAR2(100 BYTE),
  CONSTRAINT "PK_CRM_T_SALES_TEAM_IN" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_SYSTEM_PID" IS '业务主键';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_SYSTEM_CODE" IS '业务CODE';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_CENTER" IS '营销中心';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_DEPART" IS '销售部门';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_NAME" IS '人员姓名';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_RESPON" IS '责任人';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_OPERATE_UNIT" IS '业务实体';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_ROLE" IS '角色';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_AUTH" IS '权限';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_VALID_FROM" IS '有效日期从';
  COMMENT ON COLUMN "CRM_T_SALES_TEAM_IN"."C_MARK_VALID_TO" IS '有效日期至';