  CREATE TABLE "CRM_T_BIZ_PERMISSION_REL" 
  (	"C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_ORG_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_BUSINESS_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE，
  CONSTRAINT "PK_CRM_T_BIZ_PERMISSION_REL" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

  COMMENT ON COLUMN "CRM_T_BIZ_PERMISSION_REL"."C_PID" IS 'ID';
 
  COMMENT ON COLUMN "CRM_T_BIZ_PERMISSION_REL"."C_ORG_ID" IS '组织ID';
 
  COMMENT ON COLUMN "CRM_T_BIZ_PERMISSION_REL"."C_BUSINESS_ID" IS '业务ID';
