  CREATE TABLE "CRM_T_HO_CUSTOM_INFO" 
   (	"C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
   "C_BUSINESS_ID" VARCHAR2(32 BYTE), 
   "C_BUSINESS_STATUS" VARCHAR2(32 BYTE),
   "C_BASE_ID" VARCHAR2(32 BYTE),
	"C_CUSTOM_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_FULL_NAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_ALIAS_NAME" VARCHAR2(300 BYTE), 
	"C_CUSTOM_WEB_ADDRESS" VARCHAR2(300 BYTE), 
	"C_CUSTOM_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_CLASS" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_SOURCE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_STATUS" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_OEM" VARCHAR2(300 BYTE), 
	"C_CUSTOM_AREA" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_CONTROL_STATUS" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOM_GRADE" VARCHAR2(32 BYTE), 
	"C_CUSTOM_INCOME_SCALE" VARCHAR2(32 BYTE), 
	"C_CUSTOM_REPORTED_FLG" VARCHAR2(32 BYTE), 
	"C_CUSTOM_OROPERTY" VARCHAR2(32 BYTE), 
	"C_CUSTOM_CATEGORY" VARCHAR2(32 BYTE), 
	"C_CUSTOM_CATEGORY_COMMENT" VARCHAR2(300 BYTE), 
	"C_CUSTOM_PROFILE" VARCHAR2(300 BYTE), 
	"C_CORP_REPRESENTATIVE" VARCHAR2(100 BYTE), 
	"C_CORP_TRN" VARCHAR2(20 BYTE), 
	"C_CORP_PAYMENT_DEFAULT" VARCHAR2(32 BYTE), 
	"C_CORP_REG_ADDRESS" VARCHAR2(300 BYTE), 
	"C_CORP_ORDINARY_FLG" VARCHAR2(32 BYTE), 
	"C_CORP_TERM_DEFAULT" VARCHAR2(32 BYTE), 
	"C_CORP_REG_CAPTIAL" VARCHAR2(20 BYTE), 
	"C_CORP_PAY_DAYS" VARCHAR2(10 BYTE), 
	"C_CORP_CITIC_AMOUNT" VARCHAR2(20 BYTE), 
	"C_CORP_ONSALE_PRICE" VARCHAR2(20 BYTE), 
	"C_CORP_DETAIL_FLG" VARCHAR2(32 BYTE), 
	"C_CORP_PICC_AMOUNT" VARCHAR2(20 BYTE), 
	"C_CORP_INVOICE_NAME" VARCHAR2(100 BYTE), 
	"C_CORP_INVOICE_COMMENT" VARCHAR2(100 BYTE), 
	"C_LIMIT_CURRENCY" VARCHAR2(32 BYTE), 
	"C_LIMIT_AMOUNT" VARCHAR2(32 BYTE), 
	"C_LIMIT_RATE" VARCHAR2(32 BYTE), 
	"C_LIMIT_UNIT" VARCHAR2(32 BYTE), 
	"C_LIMIT_COMMENT" VARCHAR2(32 BYTE), 
	"C_LIMIT_VALID_TO" DATE, 
	"C_TEMP_CURRENCY" VARCHAR2(32 BYTE), 
	"C_TEMP_AMOUNT" VARCHAR2(32 BYTE), 
	"C_TEMP_RATE" VARCHAR2(32 BYTE), 
	"C_TEMP_UNIT" VARCHAR2(32 BYTE), 
	"C_TEMP_COMMENT" VARCHAR2(32 BYTE), 
	"C_TEMP_VALID_TO" DATE, 
	"C_PIPE_CLASS" VARCHAR2(32 BYTE), 
	"C_PIPE_ATTR" VARCHAR2(32 BYTE), 
	"C_PIPE_RANK" VARCHAR2(32 BYTE), 
	"C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_CREATED_AT" DATE, 
	"C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
	"C_CREATED_ORG_ID" VARCHAR2(100 BYTE), 
	"C_UPDATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_UPDATED_AT" DATE, 
	"C_CUSTOM_ERP_CODE" VARCHAR2(32 BYTE), 
	"C_CUSTOM_ERP_STATUS" VARCHAR2(32 BYTE), 
  CONSTRAINT "PK_HO_CUSTOM_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_PID" IS '主键自增';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_CODE" IS '客户编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_FULL_NAME" IS '客户全称';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_ALIAS_NAME" IS '客户别名';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_WEB_ADDRESS" IS '公司网址';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_TYPE" IS '客户种类 0:内部客户 1:外部客户';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_CLASS" IS '客户类别';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_SOURCE" IS '客户来源';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_STATUS" IS '客户状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_OEM" IS 'OEM 品牌';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_AREA" IS '所属区域';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_CONTROL_STATUS" IS '控制状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_GRADE" IS '客户等级';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_INCOME_SCALE" IS '收入规模';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_REPORTED_FLG" IS '已报备';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_OROPERTY" IS '客户属性';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_CATEGORY" IS '客户行业';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_CATEGORY_COMMENT" IS '行业备注';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CUSTOM_PROFILE" IS '客户概况';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_REPRESENTATIVE" IS '法定代表人';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_TRN" IS '纳税登记号';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_PAYMENT_DEFAULT" IS '默认付款方式';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_REG_ADDRESS" IS '注册地址';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_ORDINARY_FLG" IS '一般纳税人资格';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_TERM_DEFAULT" IS '默认付款条件';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_REG_CAPTIAL" IS '注册资本(CNY)';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_PAY_DAYS" IS '账期';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_CITIC_AMOUNT" IS '中信保额度(USD)';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_ONSALE_PRICE" IS '特价异常';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_DETAIL_FLG" IS '对账单显示收款明细';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_PICC_AMOUNT" IS '人保额度(USD)';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_INVOICE_NAME" IS '开票名称';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CORP_INVOICE_COMMENT" IS '开票注意事项';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_LIMIT_CURRENCY" IS '信用额度-常规-币种';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_LIMIT_AMOUNT" IS '信用额度-常规-额度';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_LIMIT_RATE" IS '信用额度-常规-汇率';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_LIMIT_UNIT" IS '信用额度-常规-业务实体';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_LIMIT_COMMENT" IS '信用额度-常规-说明';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_LIMIT_VALID_TO" IS '信用额度-常规-有效期至';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_TEMP_CURRENCY" IS '信用额度-临时-币种';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_TEMP_AMOUNT" IS '信用额度-临时-额度';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_TEMP_RATE" IS '信用额度-临时-汇率';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_TEMP_UNIT" IS '信用额度-临时-业务实体';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_TEMP_COMMENT" IS '信用额度-临时-说明';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_TEMP_VALID_TO" IS '信用额度-临时-有效期至';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_PIPE_CLASS" IS '渠道类别';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_PIPE_ATTR" IS '渠道属性';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_PIPE_RANK" IS '签约经销商等级';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CREATED_BY_ID" IS '创建人';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."DT_CREATED_AT" IS '创建时间';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."C_UPDATED_BY_ID" IS '更新者';
 
   COMMENT ON COLUMN "CRM_T_HO_CUSTOM_INFO"."DT_UPDATED_AT" IS '更新时间';
 
