  CREATE TABLE "CRM_T_HO_CONTR_BASIC" 
   (	"C_ID" VARCHAR2(32 BYTE), 
   "C_BUSINESS_ID" VARCHAR2(32 BYTE), 
   "C_BUSINESS_STATUS" VARCHAR2(32 BYTE),
   "C_BASE_ID" VARCHAR2(32 BYTE),
	"C_CONTR_VER" VARCHAR2(32 BYTE), 
	"C_CONTR_NO" VARCHAR2(32 BYTE), 
	"C_CONTR_NAME" VARCHAR2(100 BYTE), 
	"C_CONTR_TYPE" VARCHAR2(32 BYTE) DEFAULT NULL, 
	"C_CONTR_STAT" VARCHAR2(32 BYTE), 
	"C_PROJ_NAME" VARCHAR2(100 BYTE), 
	"C_PROJ_NO" VARCHAR2(32 BYTE), 
	"C_CUST_CODE" VARCHAR2(32 BYTE), 
	"C_CUST_NAME" VARCHAR2(100 BYTE), 
	"C_CUST_CONTR_NO" VARCHAR2(32 BYTE), 
	"C_CUST_LINK" VARCHAR2(100 BYTE), 
	"C_PRIC_NO" VARCHAR2(32 BYTE), 
	"C_PRIC_TABLE" VARCHAR2(100 BYTE), 
	"C_REVIEW_STAT" VARCHAR2(32 BYTE), 
	"C_TRIAL_STAT" VARCHAR2(32 BYTE), 
	"C_CANCEL_STAT" VARCHAR2(32 BYTE), 
	"C_FRAME_NO" VARCHAR2(32 BYTE), 
	"N_TOTAL_AMT" NUMBER(12,4), 
	"N_NCAN_NUM" NUMBER(12,4), 
	"N_NCAN_AMT" NUMBER(12,4), 
	"C_BUSS_ENITY" VARCHAR2(100 BYTE), 
	"C_ORG" VARCHAR2(100 BYTE), 
	"C_PAY_WAY" VARCHAR2(400 BYTE), 
	"C_PAY_COND" VARCHAR2(32 BYTE), 
	"C_IS_VALID" VARCHAR2(2 BYTE), 
	"C_IS_CHANGE" VARCHAR2(2 BYTE), 
	"C_IS_SEAL_FIRST" VARCHAR2(2 BYTE), 
	"C_IS_WHOLE_SET" VARCHAR2(2 BYTE), 
	"C_IS_CONF_LIST" VARCHAR2(2 BYTE), 
	"C_IS_DELIV_HOME" VARCHAR2(2 BYTE), 
	"C_IS_UNLOAD" VARCHAR2(2 BYTE), 
	"C_IS_HOME_INSTALL" VARCHAR2(2 BYTE), 
	"C_IS_AUX" VARCHAR2(2 BYTE), 
	"C_IS_TRANF_SALE" VARCHAR2(2 BYTE), 
	"C_POST_NO" VARCHAR2(100 BYTE), 
	"DT_POST_DATE" DATE, 
	"DT_DELIV_DATE" DATE, 
	"DT_SYS_SIGN_DATE" DATE, 
	"DT_ACT_SIGN_DATE" DATE, 
	"C_CREATOR" VARCHAR2(32 BYTE), 
	"DT_CREATE_TIME" DATE, 
	"C_CHANGER" VARCHAR2(32 BYTE), 
	"DT_CHANGE_TIME" DATE, 
	"C_SUBMITER" VARCHAR2(32 BYTE), 
	"DT_SUBMIT_TIME" DATE, 
	"C_PROC_INST_ID" VARCHAR2(32 BYTE), 
	"C_REMARK" VARCHAR2(100 BYTE), 
	"C_FINAL_REVIEW_STAT" VARCHAR2(32 BYTE), 
	"C_IS_ARCHIVE" VARCHAR2(2 BYTE), 
	"DT_ARCHIVE_DATE" DATE, 
	"C_ARCHIVE_REMARK" VARCHAR2(100 BYTE), 
	"C_PAY_STAT" VARCHAR2(32 BYTE), 
	"C_SHIP_WAY" VARCHAR2(32 BYTE), 
	"C_DIRECT_SELL_NO" VARCHAR2(32 BYTE), 
	"C_CUST_ADDR" VARCHAR2(100 BYTE), 
	"C_CUST_PHONE" VARCHAR2(100 BYTE), 
	"C_QUOT_NO" VARCHAR2(32 BYTE), 
	"DT_EXPECT_SIGN_DATE" DATE, 
	"C_CUST_LINK_ID" VARCHAR2(32 BYTE), 
	"CREATED_BY_ID" VARCHAR2(32 BYTE), 
	"CREATED_AT" DATE, 
	"CREATED_POS_ID" VARCHAR2(32 BYTE), 
	"CREATED_ORG_ID" VARCHAR2(32 BYTE), 
	"UPDATED_BY_ID" VARCHAR2(32 BYTE), 
	"UPDATED_AT" DATE, 
	"C_ERP_ORDER_CUST_ID" VARCHAR2(32 BYTE), 
	"C_ERP_ORDER_CUST_NAME" VARCHAR2(100 BYTE), 
	"C_ORDERER" VARCHAR2(32 BYTE), 
	"C_MARKET_DEPT" VARCHAR2(32 BYTE), 
	"DT_VALID_DATE" DATE, 
	"C_ORDER_NO" VARCHAR2(32 BYTE), 
	"N_TOTAL_RECEIVE_AMT" NUMBER(12,4), 
	"N_NOT_TOTAL_RECEIVE_AMT" NUMBER(12,4), 
	"N_ORDERED_AMT" NUMBER(12,4), 
	"N_DELIVERIED_AMT" NUMBER(12,4), 
	"N_INVOICED_AMT" NUMBER(12,4),
	"C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_CREATED_AT" DATE, 
	"C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
	"C_CREATED_ORG_ID" VARCHAR2(100 BYTE), 
	"C_UPDATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_HO_CONTR_BASIC" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ID" IS '主键自增';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CONTR_VER" IS '合同版本';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CONTR_NO" IS '合同编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CONTR_NAME" IS '合同名称';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CONTR_TYPE" IS '合同类型';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CONTR_STAT" IS '合同状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PROJ_NAME" IS '项目名称';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PROJ_NO" IS '项目编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_CODE" IS '客户编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_NAME" IS '客户名称';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_CONTR_NO" IS '客户合同号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_LINK" IS '客户联系人';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PRIC_NO" IS '价格表编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PRIC_TABLE" IS '报价表';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_REVIEW_STAT" IS '评审状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_TRIAL_STAT" IS '初审状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CANCEL_STAT" IS '核销状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_FRAME_NO" IS '框架协议编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_TOTAL_AMT" IS '总金额';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_NCAN_NUM" IS '未核销数量';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_NCAN_AMT" IS '未核销金额';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_BUSS_ENITY" IS '业务实体';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ORG" IS '组织';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PAY_WAY" IS '付款方式';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PAY_COND" IS '付款条件';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_VALID" IS '有效标识';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_CHANGE" IS '变更标识';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_SEAL_FIRST" IS '是否先盖章';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_WHOLE_SET" IS '是否成套';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_CONF_LIST" IS '是否有配置清单';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_DELIV_HOME" IS '是否送货上门';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_UNLOAD" IS '是否需卸货';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_HOME_INSTALL" IS '是否上门安装';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_AUX" IS '是否提供安装辅材';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_TRANF_SALE" IS '转销标识';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_POST_NO" IS '邮寄单号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_POST_DATE" IS '邮寄日期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_DELIV_DATE" IS '交货日期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_SYS_SIGN_DATE" IS '系统签订日期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_ACT_SIGN_DATE" IS '实际签订日期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_CREATE_TIME" IS '创建日期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CHANGER" IS '变更人';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_CHANGE_TIME" IS '变更日期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_SUBMITER" IS '评审提交人';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_SUBMIT_TIME" IS '提交评审时间';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PROC_INST_ID" IS '流程实例ID';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_REMARK" IS '备注';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_FINAL_REVIEW_STAT" IS '合同书评审状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_IS_ARCHIVE" IS '原件是否已归档';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_ARCHIVE_DATE" IS '原件归档时间';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ARCHIVE_REMARK" IS '归档备注';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_PAY_STAT" IS '收款计划维护状态';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_SHIP_WAY" IS '运输方式';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_DIRECT_SELL_NO" IS '直销合同号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_ADDR" IS '客户地址';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_PHONE" IS '客户电话';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_QUOT_NO" IS '报价单号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_EXPECT_SIGN_DATE" IS '合同预计签订时间';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_CUST_LINK_ID" IS '客户联系人ID';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."CREATED_BY_ID" IS '创建人';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."CREATED_AT" IS '创建时间';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."CREATED_POS_ID" IS '创建人岗位';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."CREATED_ORG_ID" IS '创建人组织';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."UPDATED_BY_ID" IS '更新者';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."UPDATED_AT" IS '更新时间';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ERP_ORDER_CUST_ID" IS 'ERP下单客户ID';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ERP_ORDER_CUST_NAME" IS 'ERP下单客户名称';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ORDERER" IS '下单商务专员';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_MARKET_DEPT" IS '营销部门';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."DT_VALID_DATE" IS '合同有效期';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."C_ORDER_NO" IS '订单编号';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_TOTAL_RECEIVE_AMT" IS '总已收金额';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_NOT_TOTAL_RECEIVE_AMT" IS '总未收金额';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_ORDERED_AMT" IS '已下单金额';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_DELIVERIED_AMT" IS '已发货金额';
 
   COMMENT ON COLUMN "CRM_T_HO_CONTR_BASIC"."N_INVOICED_AMT" IS '已开票金额';
 
