  CREATE TABLE "CRM_T_HO_ORDER_HEADER" 
   (	"C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
   "C_BUSINESS_ID" VARCHAR2(32 BYTE), 
   "C_BUSINESS_STATUS" VARCHAR2(32 BYTE),
   "C_BASE_ID" VARCHAR2(32 BYTE),
	"C_ORDER_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOMER_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"C_CUSTOMER_NAME" VARCHAR2(300 BYTE), 
	"C_CUST_ATTN_CODE" VARCHAR2(300 BYTE), 
	"C_CUST_ATTN_NAME" VARCHAR2(300 BYTE), 
	"C_CUSTOMER_PO" VARCHAR2(300 BYTE), 
	"C_DELIVERY_ADDRESS" VARCHAR2(300 BYTE), 
	"C_BILL_ADDRESS" VARCHAR2(300 BYTE), 
	"C_BUSINESS_ENTITY" VARCHAR2(300 BYTE), 
	"C_SHIP_ORG" VARCHAR2(300 BYTE), 
	"C_SOURCE_TYPE" VARCHAR2(300 BYTE), 
	"C_SOURCE_CODE" VARCHAR2(300 BYTE), 
	"C_ORDER_TYPE" VARCHAR2(300 BYTE), 
	"DT_ORDER_DATE" DATE, 
	"DT_REQUEST_DATE" DATE, 
	"C_CURRENCY" VARCHAR2(32 BYTE), 
	"C_CONVERT_TYPE" VARCHAR2(32 BYTE), 
	"DT_CONVERT_DATE" DATE, 
	"C_PRICE_TABLE_ID" VARCHAR2(32 BYTE), 
	"N_AMOUNT" NUMBER(16,4), 
	"C_REMARK" VARCHAR2(300 BYTE), 
	"C_SALESMAN_ID" VARCHAR2(32 BYTE), 
	"C_SALESMAN_CENTER" VARCHAR2(32 BYTE), 
	"C_SALESMAN_DEP" VARCHAR2(300 BYTE), 
	"C_SALES_TERRITORY" VARCHAR2(32 BYTE), 
	"C_EXECUTE_STATUS" VARCHAR2(32 BYTE), 
	"C_CONTROL_STATUS" VARCHAR2(32 BYTE), 
	"N_IS_ABNORMAL_PRICE" NUMBER(1,0), 
	"N_IS_ABNORMAL_CREDIT" NUMBER(1,0), 
	"C_TERM_PAYMENT" VARCHAR2(32 BYTE), 
	"C_TERM_PAYMENT_DETAIL" VARCHAR2(300 BYTE), 
	"C_PAYMENT_CUSTOMER_ID" VARCHAR2(32 BYTE), 
	"C_FINAL_CUST_ID" VARCHAR2(32 BYTE), 
	"C_FINAL_CUST_TRADE_B" VARCHAR2(32 BYTE), 
	"C_FINAL_CUST_TRADE_S" VARCHAR2(32 BYTE), 
	"C_IS_INSTALL" VARCHAR2(32 BYTE), 
	"C_IS_AM" VARCHAR2(32 BYTE), 
	"C_INSPECTION_CYCLE" VARCHAR2(32 BYTE), 
	"C_WARRANTY_PERIOD" VARCHAR2(32 BYTE), 
	"C_SHIP_TYPE" VARCHAR2(32 BYTE), 
	"C_IS_HOME_DELIVERY" VARCHAR2(10 BYTE), 
	"C_IS_DESTINATION_DELIVERY" VARCHAR2(10 BYTE), 
	"C_SERVICE_CLAUSE" VARCHAR2(300 BYTE), 
	"N_COLLECTION_FREIGHT" NUMBER(16,4), 
	"N_DIE_COST" NUMBER(16,4), 
	"N_DEVELOPMENT_COSTS" NUMBER(16,4), 
	"C_CUST_BRAND_CLASS" VARCHAR2(32 BYTE), 
	"C_IS_FREE_SPARE" VARCHAR2(32 BYTE), 
	"C_IS_RANDOM_SPARE" VARCHAR2(10 BYTE), 
	"N_SPARE_AMOUNT" NUMBER(16,4), 
	"N_SPARE_BALANCE" NUMBER(16,4), 
	"C_SPARE_AMOUNT_SITUATION" VARCHAR2(32 BYTE), 
	"C_SPARE_ORDER_NO" VARCHAR2(32 BYTE), 
	"C_CUSTOMER_ID" VARCHAR2(32 BYTE), 
	"C_SOURCE_NAME" VARCHAR2(300 BYTE), 
	"C_SALESMAN_NAME" VARCHAR2(300 BYTE), 
	"C_PAYMENT_CUSTOMER_NAME" VARCHAR2(300 BYTE), 
	"C_FINAL_CUST_NAME" VARCHAR2(32 BYTE), 
	"C_DELIVERY_ADDRESS_ID" VARCHAR2(32 BYTE), 
	"C_BILL_ADDRESS_ID" VARCHAR2(32 BYTE), 
	"C_ERP_ORDER_CODE" VARCHAR2(32 BYTE), 
	"C_PRICE_TABLE_NAME" VARCHAR2(300 BYTE), 
	"C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_CREATED_AT" DATE, 
	"C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
	"C_CREATED_ORG_ID" VARCHAR2(100 BYTE), 
	"C_UPDATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_UPDATED_AT" DATE, 
	"C_SOURCE_ID" VARCHAR2(32 BYTE), 
	"C_SALESMAN_CODE" VARCHAR2(100 BYTE), 
  CONSTRAINT "PK_HO_ORDER_HEADER" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_PID" IS '主键';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_ORDER_CODE" IS '订单编号';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUSTOMER_CODE" IS '客户编号';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUSTOMER_NAME" IS '客户名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUST_ATTN_CODE" IS '客户联系人编号';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUST_ATTN_NAME" IS '客户联系人名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUSTOMER_PO" IS '客户PO';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_DELIVERY_ADDRESS" IS '收货地点';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_BILL_ADDRESS" IS '收单地点';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_BUSINESS_ENTITY" IS '业务实体';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SHIP_ORG" IS '发货组织';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SOURCE_TYPE" IS '来源类型';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SOURCE_CODE" IS '来源编号';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_ORDER_TYPE" IS '订单类型';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."DT_ORDER_DATE" IS '订购日期';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."DT_REQUEST_DATE" IS '请求日期';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CURRENCY" IS '货币';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CONVERT_TYPE" IS '折换类型';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."DT_CONVERT_DATE" IS '折换日期';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_PRICE_TABLE_ID" IS '价目表ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_AMOUNT" IS '合计';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_REMARK" IS '题头备注';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SALESMAN_ID" IS '销售人员ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SALESMAN_CENTER" IS '销售人员所属中心';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SALESMAN_DEP" IS '销售人员所属部门';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SALES_TERRITORY" IS '销售区域';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_EXECUTE_STATUS" IS '执行状态';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CONTROL_STATUS" IS '控制状态';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_IS_ABNORMAL_PRICE" IS '是否价格异常';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_IS_ABNORMAL_CREDIT" IS '是否信用异常';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_TERM_PAYMENT" IS '付款条件';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_TERM_PAYMENT_DETAIL" IS '详情付款条款';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_PAYMENT_CUSTOMER_ID" IS '付款客户ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_FINAL_CUST_ID" IS '最终用户ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_FINAL_CUST_TRADE_B" IS '最终用户行业大类';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_FINAL_CUST_TRADE_S" IS '最终用户行业小类';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_IS_INSTALL" IS '是否上门安装';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_IS_AM" IS '是否所需辅材';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_INSPECTION_CYCLE" IS '巡检周期';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_WARRANTY_PERIOD" IS '保修年限';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SHIP_TYPE" IS '运输方式';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_IS_HOME_DELIVERY" IS '是否送货上门';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_IS_DESTINATION_DELIVERY" IS '是否卸货到客户指定安装地点';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SERVICE_CLAUSE" IS '售后服务条款';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_COLLECTION_FREIGHT" IS '代收运费';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_DIE_COST" IS '模具费';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_DEVELOPMENT_COSTS" IS '开发费用';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUST_BRAND_CLASS" IS '客户品牌分类';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_IS_FREE_SPARE" IS '是否免费赠送备件';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_IS_RANDOM_SPARE" IS '是否随机发赠备件';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_SPARE_AMOUNT" IS '备件额度';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."N_SPARE_BALANCE" IS '备件剩余额度';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SPARE_AMOUNT_SITUATION" IS '备件额度使用情况';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SPARE_ORDER_NO" IS '备件订单编号';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CUSTOMER_ID" IS '客户ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SOURCE_NAME" IS '来源名称，当来源为合同时为合同名称，当来源是渠道是为商机名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SALESMAN_NAME" IS '销售人员名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_PAYMENT_CUSTOMER_NAME" IS '付款客户名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_FINAL_CUST_NAME" IS '最终用户名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_DELIVERY_ADDRESS_ID" IS '收货地点ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_BILL_ADDRESS_ID" IS '收单地点ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_ERP_ORDER_CODE" IS 'ERP订单编号';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_PRICE_TABLE_NAME" IS '价目表名称';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CREATED_BY_ID" IS '创建人';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."DT_CREATED_AT" IS '创建时间';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CREATED_POS_ID" IS '创建人岗位';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_CREATED_ORG_ID" IS '创建人组织';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_UPDATED_BY_ID" IS '更新者';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."DT_UPDATED_AT" IS '更新时间';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SOURCE_ID" IS '来源ID，当来源为合同时为合同ID，当来源是渠道是为商机ID';
 
   COMMENT ON COLUMN "CRM_T_HO_ORDER_HEADER"."C_SALESMAN_CODE" IS '销售人员编号';
 
   COMMENT ON TABLE "CRM_T_HO_ORDER_HEADER"  IS '订单头表';
 
