
  CREATE TABLE "CRM_T_HO_BUSINESS_OPPORTUNITY" 
   (	"C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
   "C_BUSINESS_ID" VARCHAR2(32 BYTE), 
   "C_BUSINESS_STATUS" VARCHAR2(32 BYTE), 
   "C_BASE_ID" VARCHAR2(32 BYTE),
	"C_SALE_STAGE" VARCHAR2(32 BYTE), 
	"C_BUSINESS_PROCESS" VARCHAR2(32 BYTE), 
	"C_ENTERPRISE" VARCHAR2(32 BYTE), 
	"C_NUMBER" VARCHAR2(32 BYTE), 
	"C_STATUS" VARCHAR2(33 BYTE), 
	"C_SALER_ID" VARCHAR2(32 BYTE), 
	"C_SALER_NAME" VARCHAR2(32 BYTE), 
	"C_CREATER" VARCHAR2(32 BYTE), 
	"C_CONFLICT_STATUS" VARCHAR2(32 BYTE), 
	"C_SALER_PHONE" VARCHAR2(20 BYTE), 
	"DT_CREATE_TIME" TIMESTAMP (6), 
	"C_CONFLICT_NUMBER" VARCHAR2(32 BYTE), 
	"C_CLIENT_ID" VARCHAR2(32 BYTE), 
	"C_CLIENT_NAME" VARCHAR2(80 BYTE), 
	"C_INDUSTRY" VARCHAR2(80 BYTE), 
	"C_BID_UNIT" VARCHAR2(80 BYTE), 
	"C_KEY_CONTACT" VARCHAR2(80 BYTE), 
	"C_CONTACT_DEPT" VARCHAR2(80 BYTE), 
	"C_CONTACT_PHONE" VARCHAR2(20 BYTE), 
	"C_OPPORTUNITY_NAME" VARCHAR2(80 BYTE), 
	"C_ADDRESS" VARCHAR2(80 BYTE), 
	"DT_PLAN_FIN_DATE" TIMESTAMP (6), 
	"C_SALE_METHOD" VARCHAR2(32 BYTE), 
	"N_SUCCESS_RATE" VARCHAR2(32 BYTE), 
	"C_PROJECT_SITUATION" VARCHAR2(300 BYTE), 
	"C_PROJECT_PROGRESS" VARCHAR2(300 BYTE), 
	"N_IS_INTEGREATED" NUMBER, 
	"C_BIZ_OPP_ADDRESS" VARCHAR2(32 BYTE), 
	"C_SOURCE" VARCHAR2(32 BYTE), 
	"C_CURRENCY" VARCHAR2(32 BYTE), 
	"N_ESTIMATED_AMOUNT" NUMBER(32,4), 
	"DT_UPDATE_TIME" TIMESTAMP (6), 
	"C_COMPETITIVE_BRANDS" VARCHAR2(32 BYTE), 
	"C_BIZ_OPP_ADDRESS_NAME" VARCHAR2(100 BYTE), 
	"C_PROJECT_TYPE" VARCHAR2(30 BYTE), 
	"C_QOUT_NAME" VARCHAR2(100 BYTE), 
	"C_IS_BID_PROJECT" VARCHAR2(30 BYTE), 
	"C_IS_PRO_REVIEW" VARCHAR2(30 BYTE), 
	"C_CONTRNAME" VARCHAR2(100 BYTE), 
	"C_PRODUCT_PROJECT" VARCHAR2(100 BYTE), 
	"C_BID_NO" VARCHAR2(50 BYTE), 
	"C_IS_INTEGRATION" VARCHAR2(32 BYTE), 
	"IS_UNION_BID" VARCHAR2(32 BYTE), 
	"UNION_CONTACT" VARCHAR2(32 BYTE), 
	"UNION_POSITION" VARCHAR2(32 BYTE), 
	"UNION_NAME" VARCHAR2(32 BYTE), 
	"UNION_ADDRESS" VARCHAR2(100 BYTE), 
	"UNION_PHONE" VARCHAR2(32 BYTE), 
	"UNION_LEGAL" VARCHAR2(32 BYTE), 
	"UNION_EMAIL" VARCHAR2(32 BYTE), 
	"SBU_FLAG" VARCHAR2(32 BYTE), 
	"C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_CREATED_AT" DATE, 
	"C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
	"C_CREATED_ORG_ID" VARCHAR2(100 BYTE), 
	"C_UPDATED_BY_ID" VARCHAR2(100 BYTE), 
	"DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_HO_BUSINESS_OPPORTUNITY" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
 

   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_PID" IS 'primary key';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_SALE_STAGE" IS '销售阶段';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_BUSINESS_PROCESS" IS '业务流程';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_ENTERPRISE" IS '报备单位';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_NUMBER" IS '商机编号';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_STATUS" IS '状态';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_SALER_ID" IS '销售ID';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_SALER_NAME" IS '销售员';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CREATER" IS '报备人';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CONFLICT_STATUS" IS '冲突状态';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_SALER_PHONE" IS '销售员电话';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."DT_CREATE_TIME" IS '创建日期';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CONFLICT_NUMBER" IS '冲突管理单';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CLIENT_ID" IS '客户ID';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CLIENT_NAME" IS '客户名称';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_INDUSTRY" IS '行业';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_BID_UNIT" IS '招标单位';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_KEY_CONTACT" IS '主要联系人';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CONTACT_DEPT" IS '联系人部门';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CONTACT_PHONE" IS '联系人电话';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_OPPORTUNITY_NAME" IS '商机名称';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_ADDRESS" IS '详细地址';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."DT_PLAN_FIN_DATE" IS '预计成交时间';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_SALE_METHOD" IS '销售方法';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."N_SUCCESS_RATE" IS '成功率';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_PROJECT_SITUATION" IS '项目概况';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_PROJECT_PROGRESS" IS '项目推动情况';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."N_IS_INTEGREATED" IS '是否集成包';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_BIZ_OPP_ADDRESS" IS '商机所在地';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_SOURCE" IS '来源';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CURRENCY" IS '币种';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."N_ESTIMATED_AMOUNT" IS '预计金额';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."DT_UPDATE_TIME" IS '更新时间';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_COMPETITIVE_BRANDS" IS '竞争品牌';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_BIZ_OPP_ADDRESS_NAME" IS '商机所在地名称';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_PROJECT_TYPE" IS '立项类型';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_QOUT_NAME" IS '报价单名称';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_IS_BID_PROJECT" IS '是否投标类型';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_IS_PRO_REVIEW" IS '是否工程评审';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CONTRNAME" IS '合同名称';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CREATED_POS_ID" IS '创建人岗位';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_CREATED_ORG_ID" IS '创建人组织';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_UPDATED_BY_ID" IS '更新者';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_PRODUCT_PROJECT" IS '产品项目';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_BID_NO" IS '招标号';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."C_IS_INTEGRATION" IS '是否集成案';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."IS_UNION_BID" IS '是否联合体投标';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_CONTACT" IS '业务联系人';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_POSITION" IS '职务';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_NAME" IS '联合单位名称';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_ADDRESS" IS '地址';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_PHONE" IS '电话';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_LEGAL" IS '法人代表';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."UNION_EMAIL" IS 'email';
 
   COMMENT ON COLUMN "CRM_T_HO_BUSINESS_OPPORTUNITY"."SBU_FLAG" IS '1国内,2光伏';
 
   COMMENT ON TABLE "CRM_T_HO_BUSINESS_OPPORTUNITY"  IS '商机信息表';
 
