--客户信息

CREATE TABLE "CRM_T_CUSTOM_INFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_CODE" VARCHAR2(32 BYTE) , 
  "C_CUSTOM_ERP_CODE" VARCHAR2(32 BYTE) , 
  "C_CUSTOM_PRM_FLG" VARCHAR2(32 BYTE) , 
  "C_CUSTOM_ERP_STATUS" VARCHAR2(32 BYTE) , 
  "C_CUSTOM_FULL_NAME" VARCHAR2(300 BYTE),  
  "C_CUSTOM_ALIAS_NAME" VARCHAR2(300 BYTE), 
  "C_CUSTOM_WEB_ADDRESS" VARCHAR2(300 BYTE), 
  "C_CUSTOM_TYPE" VARCHAR2(1 BYTE) ,  
  "C_CUSTOM_CLASS" VARCHAR2(32 BYTE)  ,  
  "C_CUSTOM_SOURCE" VARCHAR2(32 BYTE)  ,  
  "C_CUSTOM_STATUS" VARCHAR2(32 BYTE) ,  
  "C_CUSTOM_OEM" VARCHAR2(300 BYTE), 
  "C_CUSTOM_AREA" VARCHAR2(32 BYTE) , 
  "C_CUSTOM_AREA_SUB1" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_AREA_SUB2" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_AREA_SUB3" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_CONTROL_STATUS" VARCHAR2(32 BYTE) , 
  "C_CUSTOM_GRADE" VARCHAR2(32 BYTE),
  "C_CUSTOM_INCOME_SCALE" VARCHAR2(32 BYTE),
  "C_CUSTOM_REPORTED_FLG" VARCHAR2(32 BYTE),
  "C_CUSTOM_OROPERTY" VARCHAR2(32 BYTE),
  "C_CUSTOM_CATEGORY" VARCHAR2(32 BYTE),
  "C_CUSTOM_CATEGORY_SUB" VARCHAR2(32 BYTE),
  "C_CUSTOM_CATEGORY_COMMENT" VARCHAR2(300 BYTE),
  "C_CUSTOM_PROFILE" VARCHAR2(300 BYTE),
  "C_CORP_REPRESENTATIVE" VARCHAR2(100 BYTE) , 
  "C_CORP_TRN" VARCHAR2(20 BYTE), 
  "C_CORP_PAYMENT_DEFAULT" VARCHAR2(32 BYTE),
  "C_CORP_REG_ADDRESS" VARCHAR2(300 BYTE) , 
  "C_CONTACT_NAME" VARCHAR2(300 BYTE) , 
  "C_CONTACT_DEPT" VARCHAR2(300 BYTE) , 
  "C_CONTACT_BUSINESS" VARCHAR2(300 BYTE) , 
  "C_CONTACT_ROLE" VARCHAR2(300 BYTE) , 
  "C_CONTACT_TEL" VARCHAR2(300 BYTE) , 
  "C_CORP_ORDINARY_FLG" VARCHAR2(32 BYTE),
  "C_CORP_TERM_DEFAULT" VARCHAR2(32 BYTE),
  "C_CORP_REG_CAPTIAL" VARCHAR2(20 BYTE), 
  "C_CORP_PAY_DAYS" VARCHAR2(10 BYTE),
  "C_CORP_CITIC_AMOUNT" VARCHAR2(20 BYTE),
  "C_CORP_ONSALE_PRICE" VARCHAR2(20 BYTE),
  "C_CORP_DETAIL_FLG" VARCHAR2(32 BYTE),
  "C_CORP_PICC_AMOUNT" VARCHAR2(20 BYTE),
  "C_CORP_INVOICE_NAME" VARCHAR2(100 BYTE), 
  "C_CORP_INVOICE_COMMENT" VARCHAR2(100 BYTE),
  "C_CREDIT_ID" VARCHAR2(32 BYTE) ,
  "C_LIMIT_CURRENCY" VARCHAR2(32 BYTE) , 
  "C_LIMIT_AMOUNT" VARCHAR2(32 BYTE) , 
  "C_LIMIT_RATE" VARCHAR2(32 BYTE) , 
  "C_LIMIT_UNIT" VARCHAR2(32 BYTE) , 
  "C_LIMIT_COMMENT" VARCHAR2(32 BYTE) , 
  "C_LIMIT_VALID_TO" DATE , 
  "C_TEMP_CURRENCY" VARCHAR2(32 BYTE) , 
  "C_TEMP_AMOUNT" VARCHAR2(32 BYTE) , 
  "C_TEMP_RATE" VARCHAR2(32 BYTE) , 
  "C_TEMP_UNIT" VARCHAR2(32 BYTE) , 
  "C_TEMP_COMMENT" VARCHAR2(32 BYTE) , 
  "C_TEMP_VALID_TO" DATE , 
  "C_PIPE_CLASS" VARCHAR2(32 BYTE) , 
  "C_PIPE_ATTR" VARCHAR2(32 BYTE) , 
  "C_PIPE_RANK" VARCHAR2(32 BYTE), 
  "C_ACCOUNT_ADDRESS" VARCHAR2(300 BYTE), 
  "C_ACCOUNT_BANK" VARCHAR2(300 BYTE), 
  "C_ACCOUNT_TEL" VARCHAR2(300 BYTE), 
  "C_ACCOUNT_NO" VARCHAR2(300 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_CODE" IS '客户编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_PRM_FLG" IS 'CRM/PRM FLAG';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_ERP_CODE" IS 'ERP编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_ERP_STATUS" IS 'ERP引入状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_FULL_NAME" IS '客户全称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_ALIAS_NAME" IS '客户别名';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_WEB_ADDRESS" IS '公司网址';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_TYPE" IS '客户种类 0:内部客户 1:外部客户';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_CLASS" IS '客户类别';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_SOURCE" IS '客户来源';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_STATUS" IS '客户状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_OEM" IS 'OEM 品牌';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_AREA" IS '所属区域 国家';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_AREA_SUB1" IS '所属区域 省';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_AREA_SUB1" IS '所属区域 市';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_AREA_SUB1" IS '所属区域 区县';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_CONTROL_STATUS" IS '控制状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_GRADE" IS '客户等级';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_INCOME_SCALE" IS '收入规模';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_REPORTED_FLG" IS '已报备';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_OROPERTY" IS '客户属性';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_CATEGORY" IS '客户行业 大类';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_CATEGORY_SUB" IS '客户行业 小类';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_CATEGORY_COMMENT" IS '行业备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CUSTOM_PROFILE" IS '客户概况';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_REPRESENTATIVE" IS '法定代表人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_TRN" IS '纳税登记号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_PAYMENT_DEFAULT" IS '默认付款方式';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_REG_ADDRESS" IS '注册地址';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CONTACT_NAME" IS '名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CONTACT_DEPT" IS '部门';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CONTACT_BUSINESS" IS '职务';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CONTACT_ROLE" IS '角色';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CONTACT_TEL" IS '电话';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_ORDINARY_FLG" IS '一般纳税人资格';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_TERM_DEFAULT" IS '默认付款条件';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_REG_CAPTIAL" IS '注册资本(CNY)';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_PAY_DAYS" IS '账期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_CITIC_AMOUNT" IS '中信保额度(USD)';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_ONSALE_PRICE" IS '特价异常';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_DETAIL_FLG" IS '对账单显示收款明细';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_PICC_AMOUNT" IS '人保额度(USD)';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_INVOICE_NAME" IS '开票名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CORP_INVOICE_COMMENT" IS '开票注意事项';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CREDIT_ID" IS '信用调整主键'; 
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_LIMIT_CURRENCY" IS '信用额度-常规-币种';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_LIMIT_AMOUNT" IS '信用额度-常规-额度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_LIMIT_RATE" IS '信用额度-常规-汇率';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_LIMIT_UNIT" IS '信用额度-常规-业务实体';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_LIMIT_COMMENT" IS '信用额度-常规-说明';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_LIMIT_VALID_TO" IS '信用额度-常规-有效期至';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_TEMP_CURRENCY" IS '信用额度-临时-币种';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_TEMP_AMOUNT" IS '信用额度-临时-额度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_TEMP_RATE" IS '信用额度-临时-汇率';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_TEMP_UNIT" IS '信用额度-临时-业务实体';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_TEMP_COMMENT" IS '信用额度-临时-说明';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_TEMP_VALID_TO" IS '信用额度-临时-有效期至';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_PIPE_CLASS" IS '渠道类别';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_PIPE_ATTR" IS '渠道属性';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_PIPE_RANK" IS '签约经销商等级';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_ACCOUNT_ADDRESS" IS '开票地址';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_ACCOUNT_BANK" IS '开户行';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_ACCOUNT_TEL" IS '开票电话';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_ACCOUNT_NO" IS '开户账号';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO"."DT_UPDATED_AT" IS '更新时间';

--需求产品
  
CREATE TABLE "CRM_T_CUSTOM_REQUIRE_INFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_REQUIRE_CLASS" VARCHAR2(300 BYTE),
  "C_CUSTOM_REQUIRE_COMMENT" VARCHAR2(300 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_REQUIRE_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CUSTOM_REQUIRE_CLASS" IS '需求产品-产品类别';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CUSTOM_REQUIRE_COMMENT" IS '需求产品-备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."DT_UPDATED_AT" IS '更新时间';
  
  
--地址信息

CREATE TABLE "CRM_T_CUSTOM_ADDRESS_INFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_AREA_LOV1" VARCHAR2(32 BYTE) ,
  "C_AREA_LOV2" VARCHAR2(32 BYTE) ,
  "C_AREA_LOV3" VARCHAR2(32 BYTE) ,
  "C_AREA_LOV4" VARCHAR2(32 BYTE) ,
  "C_AREA_LOV5" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_ADDRESS" VARCHAR2(300 BYTE),
  "C_CUSTOM_ZIP" VARCHAR2(20 BYTE),
  "C_CUSTOM_ADDRESS_TYPE" VARCHAR2(300 BYTE),
  "C_CUSTOM_ADDRESS_PHONE" VARCHAR2(300 BYTE),
  "C_CUSTOM_ADDRESS_FAX" VARCHAR2(300 BYTE),
  "C_CUSTOM_ADDRESS_USE" VARCHAR2(300 BYTE),
  "C_CUSTOM_ADDRESS_VALID" VARCHAR2(32 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_ADDRESS_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_AREA_LOV1" IS '区域大分类';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_AREA_LOV2" IS '区域中分类1';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_AREA_LOV3" IS '区域中分类2';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_AREA_LOV4" IS '区域小分类1';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_AREA_LOV5" IS '区域小分类2';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ADDRESS" IS '地址';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ZIP" IS '邮政编码';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ADDRESS_TYPE" IS '地址-类型';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ADDRESS_PHONE" IS '地址-电话';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ADDRESS_FAX" IS '地址-传真';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ADDRESS_USE" IS '地址-用途';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CUSTOM_ADDRESS_VALID" IS '地址-有效';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ADDRESS_INFO"."DT_UPDATED_AT" IS '更新时间';

  
--财务信息(付款信息)

CREATE TABLE "CRM_T_CUSTOM_FINANCE_PINFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CORP_INVOICE_BANK" VARCHAR2(100 BYTE), 
  "C_CORP_INVOICE_ACCOUNT" VARCHAR2(20 BYTE), 
  "C_CORP_INVOICE_BANK_STA" VARCHAR2(32 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_FINANCE_PINFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_REQUIRE_INFO"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_CORP_INVOICE_BANK" IS '开票银行';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_CORP_INVOICE_ACCOUNT" IS '银行账号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_CORP_INVOICE_BANK_STA" IS '银行状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_FINANCE_PINFO"."DT_UPDATED_AT" IS '更新时间';
  
  
--财务信息(ERP引入)

CREATE TABLE "CRM_T_CUSTOM_ERP_INFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CORP_ERP_UNIT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  "C_CORP_LEADED_ADDRESS" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_CORP_LEADED_COMMENT" VARCHAR2(100 BYTE), 
  "C_CORP_ERP_STATUS" VARCHAR2(32 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_ERP_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CORP_ERP_UNIT" IS '业务实体';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CORP_LEADED_ADDRESS" IS '引入地址';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CORP_LEADED_COMMENT" IS '引入说明';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CORP_ERP_STATUS" IS '状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_ERP_INFO"."DT_UPDATED_AT" IS '更新时间';
  
  
--客户信息(公司关系-相关公司)

CREATE TABLE "CRM_T_CUSTOM_RELATION" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_COMP_CODE" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
  "C_CUSTOM_RELATION_LVL" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
  "C_CUSTOM_RELATE_VALID_FROM" DATE,
  "C_CUSTOM_RELATE_VALID_TO" DATE,
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE,
  CONSTRAINT "PK_CRM_T_CUSTOM_RELATION" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CUSTOM_CODE" IS '客户编码';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CUSTOM_COMP_CODE" IS '相关公司编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CUSTOM_RELATION_LVL" IS '相关公司关系';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CUSTOM_RELATE_VALID_FROM" IS '有效日期从';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CUSTOM_RELATE_VALID_TO" IS '有效日期至';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELATION"."DT_UPDATED_AT" IS '更新时间';
  
--客户信息(公司关系-联系人)

CREATE TABLE "CRM_T_CUSTOM_RELA_CONTACT" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CONTACT_NAME" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_CONTACT_SEX" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_CONTACT_AGE" VARCHAR2(3 BYTE) , 
  "C_CONTACT_WEIGHT" VARCHAR2(200 BYTE) , 
  "C_CONTACT_APPEAL" VARCHAR2(200 BYTE) , 
  "C_CONTACT_INTEREST" VARCHAR2(200 BYTE) , 
  "C_CONTACT_DEPT" VARCHAR2(100 BYTE), 
  "C_CONTACT_BUSINESS" VARCHAR2(100 BYTE), 
  "C_CONTACT_COMPETENT" VARCHAR2(100 BYTE), 
  "C_CONTACT_ROLE" VARCHAR2(100 BYTE), 
  "C_CONTACT_TEL" VARCHAR2(100 BYTE), 
  "C_CONTACT_FAX" VARCHAR2(100 BYTE), 
  "C_CONTACT_MAIL" VARCHAR2(100 BYTE), 
  "C_CONTACT_VALID" VARCHAR2(32 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE,
  CONSTRAINT "PK_CRM_T_CUSTOM_RELA_CONTACT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_NAME" IS '名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_SEX" IS '性别';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_AGE" IS '年龄';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_WEIGHT" IS '决策权重';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_APPEAL" IS '利益诉求';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_INTEREST" IS '兴趣爱好';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_DEPT" IS '部门';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_BUSINESS" IS '职务';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_COMPETENT" IS '主管领域';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_ROLE" IS '角色';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_TEL" IS '电话';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_FAX" IS '传真';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_MAIL" IS 'E-MAIL';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CONTACT_VALID" IS '有效';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_RELA_CONTACT"."DT_UPDATED_AT" IS '更新时间';
  
--客户信息(经销商-经销范围)

CREATE TABLE "CRM_T_CUSTOM_DISTR_SCOPE" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_DISTR_SCOPE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_DISTR_ALLOW" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_DISTR_COMMENT" VARCHAR2(100 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_DISTR_SCOPE" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_DISTR_SCOPE" IS '产品范围';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_DISTR_ALLOW" IS '允许经销';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_DISTR_COMMENT" IS '备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_DISTR_SCOPE"."DT_UPDATED_AT" IS '更新时间';
  
--活动信息
  
  CREATE TABLE "CRM_T_CUSTOM_EVENT_INFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_EVENT_CODE" VARCHAR2(32 BYTE) ENABLE,
  "C_CUSTOM_CODE" VARCHAR2(32 BYTE) ENABLE, 
  "C_CUSTOM_FULL_NAME" VARCHAR2(300 BYTE) , 
  "C_BIZOPP_CODE" VARCHAR2(100 BYTE), 
  "C_BIZOPP_NAME" VARCHAR2(100 BYTE) , 
  "C_EVENT_CREATE_DATE"  VARCHAR2(20 BYTE) ,
  "C_EVENT_STATUS" VARCHAR2(100 BYTE), 
  "C_EVENT_VISIT_TERM" DATE,
  "C_CREATE_CONTACT" VARCHAR2(32 BYTE),
  "C_EVENT_STAY_DAYS" VARCHAR2(100 BYTE),
  "C_EVENT_GOAL" VARCHAR2(100 BYTE),
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_PERSON_CNT" VARCHAR2(32 BYTE),
  "C_CUSTOM_GRADE" VARCHAR2(32 BYTE),
  "C_EVENT_LEL" VARCHAR2(32 BYTE),
  "C_EVENT_BEAR_PLAN" VARCHAR2(32 BYTE),
  "N_IS_1" VARCHAR2(32 BYTE),
  "N_IS_2" VARCHAR2(32 BYTE),
  "N_IS_3" VARCHAR2(32 BYTE),
  "N_IS_4" VARCHAR2(32 BYTE),
  "N_IS_5" VARCHAR2(32 BYTE),
  "N_IS_6" VARCHAR2(32 BYTE),
  "N_IS_7" VARCHAR2(32 BYTE),
  "N_IS_11" VARCHAR2(32 BYTE),
  "N_IS_12" VARCHAR2(32 BYTE),
  "N_IS_13" VARCHAR2(32 BYTE),
  "N_IS_14" VARCHAR2(32 BYTE),
  "N_IS_15" VARCHAR2(32 BYTE),
  "N_IS_16" VARCHAR2(32 BYTE),
  "N_IS_17" VARCHAR2(32 BYTE),
  "N_IS_18" VARCHAR2(32 BYTE),
  "C_MOBILE" VARCHAR2(32 BYTE),
  "C_CHARGE_PERSON" VARCHAR2(32 BYTE),
  "C_EVENT_PROFILE" VARCHAR2(100 BYTE),
  "C_EVENT_DEPARTURE_DATE" DATE,
  "C_EVENT_DEPARTURE_TIME" VARCHAR2(32 BYTE),
  "C_EVENT_ARRIVAL_DATE" DATE,
  "C_EVENT_ARRIVAL_TIME" VARCHAR2(32 BYTE),
  "C_EVENT_ARRIVAL_LOCATION" VARCHAR2(100 BYTE),
  "C_EVENT_FLIGHT" VARCHAR2(100 BYTE),
  "C_EVENT_ACCO_LABEL" VARCHAR2(100 BYTE),
  "C_EVENT_FOOD_LABEL" VARCHAR2(100 BYTE),
  "C_EVENT_LEAD_IN" VARCHAR2(100 BYTE),
  "C_EVENT_TECT" VARCHAR2(100 BYTE),
  "C_EVENT_BEAR_DEAPRTMENT" VARCHAR2(100 BYTE),
  "C_EVENT_AIM" VARCHAR2(100 BYTE),
  "C_EVENT_GIFT" VARCHAR2(100 BYTE),
  "C_EVENT_PLAN" VARCHAR2(1000 BYTE),
  "C_EVENT_OTHER" VARCHAR2(100 BYTE),
  "C_EVENT_ACTUAL_DAYS" VARCHAR2(100 BYTE),
  "C_EVENT_EVALUATION" VARCHAR2(100 BYTE),
  "C_EVENT_RESULT" VARCHAR2(100 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_EVENT_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_CODE" IS '活动编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CUSTOM_CODE" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CUSTOM_FULL_NAME" IS '客户名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_BIZOPP_CODE" IS '商机编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_BIZOPP_NAME" IS '商机名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_CREATE_DATE" IS '创建日期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_STATUS" IS '活动状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CREATE_CONTACT" IS '联系方式';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_VISIT_TERM" IS '客户来访时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_STAY_DAYS" IS '逗留天数';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_GOAL" IS '活动目的';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."APPLIER_ID" IS '申请人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."APPLIER_POS_ID" IS '申请人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."APPLIER_ORG_ID" IS '申请人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_PROFILE" IS '情况概述';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_DEPARTURE_DATE" IS '客户启程日期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_DEPARTURE_TIME" IS '客户启程时间';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_ARRIVAL_DATE" IS '预计到达日期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_ARRIVAL_TIME" IS '预计到达时间';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_ARRIVAL_LOCATION" IS '到达地点';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_FLIGHT" IS '车(船)次航班';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_ACCO_LABEL" IS '住宿标准';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_FOOD_LABEL" IS '餐饮标准';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_LEAD_IN" IS '高层领导参加';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_TECT" IS '讲解PPT及技术';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_BEAR_DEAPRTMENT" IS '承担部门';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_BEAR_DEAPRTMENT" IS '客户关注点';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_GIFT" IS '是否赠送礼品及规格';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_PLAN" IS '行程安排';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_OTHER" IS '其他要求';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_ACTUAL_DAYS" IS '实际逗留天数';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_EVALUATION" IS '效果评估';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_RESULT" IS '效果概述';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."DT_UPDATED_AT" IS '更新时间';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_PERSON_CNT" IS '来访人数';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CUSTOM_GRADE" IS '客户等级';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_LEL" IS '客户重要程度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_EVENT_BEAR_PLAN" IS '承担方案';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_1" IS '客户关注点 技术';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_2" IS '客户关注点 规模';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_3" IS '客户关注点 生产';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_4" IS '客户关注点 体系';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_5" IS '客户关注点 价格';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_6" IS '客户关注点 服务';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_7" IS '客户关注点 其他';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_11" IS '协助事项 会议室准备';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_12" IS '协助事项 展厅准备';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_13" IS '协助事项 公司介绍';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_14" IS '协助事项 技术交流';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_15" IS '协助事项 生产参观';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_16" IS '协助事项 高层接待';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_17" IS '协助事项 制作欢迎牌';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."N_IS_18" IS '协助事项 样板项目参观';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_MOBILE" IS '手机';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_INFO"."C_CHARGE_PERSON" IS '负责人';
  
  --活动信息(人员名单)

  CREATE TABLE "CRM_T_CUSTOM_EVENT_CONTACT" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_EVENT_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
"C_NAME" VARCHAR2(100 BYTE), 
"C_SEX" VARCHAR2(100 BYTE), 
"C_POST" VARCHAR2(100 BYTE), 
"C_TEL" VARCHAR2(100 BYTE), 
"C_COMMENT" VARCHAR2(100 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE,
  CONSTRAINT "PK_CRM_T_CUSTOM_EVENT_CONTACT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_EVENT_PID" IS '客户信息主键';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_NAME" IS '姓名';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_SEX" IS '性别';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_POST" IS '职务';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_TEL" IS '联系电话';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_CONTACT"."C_COMMENT" IS '备注';

--活动信息(协助事项)

CREATE TABLE "CRM_T_CUSTOM_EVENT_ITEMS" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_EVENT_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
"C_ITEM" VARCHAR2(100 BYTE), 
"C_COMMENT" VARCHAR2(100 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE,
  CONSTRAINT "PK_CRM_T_CUSTOM_EVENT_ITEMS" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_ITEMS"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_ITEMS"."C_EVENT_PID" IS '客户信息主键';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_ITEMS"."C_ITEM" IS '协助事项';
COMMENT ON COLUMN "CRM_T_CUSTOM_EVENT_ITEMS"."C_COMMENT" IS '备注';

--分享信息
  CREATE TABLE "CRM_T_CUSTOM_SHARE_INFO" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_SHARE_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_CUSTOM_FULL_NAME" VARCHAR2(300 BYTE)  NOT NULL ENABLE, 
  "C_SHARE_STATUS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  "C_SHARE_CREATE_TIME" VARCHAR2(32 BYTE),
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_SHARE_CREATE_REASON" VARCHAR2(100 BYTE), 
  "C_SHARE_DEPT" VARCHAR2(100 BYTE), 
  "C_SHARE_SALE" VARCHAR2(100 BYTE), 
  "C_SHARE_COMMENT" VARCHAR2(100 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_SHARE_INFO" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_CODE" IS '分享编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_CUSTOM_PID" IS '客户信息主键';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_CUSTOM_FULL_NAME" IS '客户名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_STATUS" IS '申请状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_CREATE_TIME" IS '申请时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."APPLIER_ID" IS '申请人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."APPLIER_POS_ID" IS '申请人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."APPLIER_ORG_ID" IS '申请人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_CREATE_REASON" IS '申请原因';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_DEPT" IS '归属部门';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_SALE" IS '归属销售员';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_SHARE_COMMENT" IS '原因描述';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_SHARE_INFO"."DT_UPDATED_AT" IS '更新时间';
  
--交接信息

CREATE TABLE "CRM_T_CUSTOM_HANDOVER_LIST" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_HANDOVER_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_HANDOVER_STATUS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  "C_HANDOVER_DATE"  VARCHAR2(32 BYTE),
  "C_CUSTOM_ID"  VARCHAR2(32 BYTE),
  "C_HANDOVER_FROM_ORG"  VARCHAR2(32 BYTE),
  "C_HANDOVER_TO_ORG"  VARCHAR2(32 BYTE),
  "C_HANDOVER_REASON" VARCHAR2(100 BYTE), 
  "C_HANDOVER_FROM" VARCHAR2(100 BYTE),
  "C_HANDOVER_TO" VARCHAR2(100 BYTE),
  "C_HANDOVER_COMMENT" VARCHAR2(100 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_HANDOVER_LIST" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_CODE" IS '交接编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_STATUS" IS '申请状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_DATE" IS '申请日期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_CUSTOM_ID" IS '指定抽取客户ID';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_FROM_ORG" IS '交接人部门';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_TO_ORG" IS '交接至部门';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_REASON" IS '交接原因';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_FROM" IS '交接人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_TO" IS '交接至';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_HANDOVER_COMMENT" IS '备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_LIST"."DT_UPDATED_AT" IS '更新时间';
  

  --交接信息(交接单据)
CREATE TABLE "CRM_T_CUSTOM_HANDOVER_RECEIPT" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_SYSTEM_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_USER_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_CUSTOM_FULL_NAME" VARCHAR2(200 BYTE),
  "C_OPPORTUNITY_NAME" VARCHAR2(32 BYTE), 
  "C_OPPORTUNITY_STATUS" VARCHAR2(32 BYTE),
  "C_QUOT_ID" VARCHAR2(32 BYTE) , 
  "C_QUOT_STATUS" VARCHAR2(32 BYTE),
  "C_CONTR_NO" VARCHAR2(32 BYTE) , 
  "C_CONTR_STAT" VARCHAR2(32 BYTE),
  "C_ORDER_CODE" VARCHAR2(32 BYTE) , 
  "C_ORDER_STATUS" VARCHAR2(32 BYTE),
  "C_DELIVERY_AMOUNT" VARCHAR2(32 BYTE),
  "C_RECEIPT_BALANCE" VARCHAR2(32 BYTE),
  "C_PAYMENT_BALANCE" VARCHAR2(32 BYTE),
  "C_COMMENT" VARCHAR2(100 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_HANDOVER_RECEIPT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_SYSTEM_ID" IS '交接ID';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_USER_ID" IS '交接人ID';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CUSTOM_CODE" IS '客户编码';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CUSTOM_FULL_NAME" IS '客户名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_OPPORTUNITY_NAME" IS '商机名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_OPPORTUNITY_STATUS" IS '商机状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_QUOT_ID" IS '报价单编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_QUOT_STATUS" IS '报价单状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CONTR_NO" IS '合同编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CONTR_STAT" IS '合同状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_ORDER_CODE" IS '订单编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_ORDER_STATUS" IS '订单状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_DELIVERY_AMOUNT" IS '发货金额';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_RECEIPT_BALANCE" IS '开票余额';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_PAYMENT_BALANCE" IS '收款余额';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_COMMENT" IS '备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_RECEIPT"."DT_UPDATED_AT" IS '更新时间';

  --交接信息(未结事务)
  
  CREATE TABLE "CRM_T_CUSTOM_HANDOVER_PROC" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_HANDOVER_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_BUSINESS_OPPO_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_BIZOPP_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  "C_CONTRACT_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_CONTRACT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  "C_GOINGON_PROC" VARCHAR2(100 BYTE),
  "C_COMMENT" VARCHAR2(100 BYTE), 
  "C_CONTINUE_BY" VARCHAR2(100 BYTE),
  "C_FINISH_FLG" VARCHAR2(100 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_HANDOVER_PROC" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_HANDOVER_CODE" IS '交接编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_BUSINESS_OPPO_CODE" IS '商机编码';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_BIZOPP_NAME" IS '商机名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_CONTRACT_CODE" IS '合同编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_CONTRACT_NAME" IS '合同名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_GOINGON_PROC" IS '未尽事项';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_COMMENT" IS '详细描述';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_CONTINUE_BY" IS '后续工作及对接人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_FINISH_FLG" IS '已完成';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_HANDOVER_PROC"."DT_UPDATED_AT" IS '更新时间';
  
  --信用评估调整
CREATE TABLE "CRM_T_CUSTOM_CREDIT_ADJUSTMENT" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_CREDIT_ADJUSTMENT_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_FULL_NAME" VARCHAR2(300 BYTE)  NOT NULL ENABLE, 
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_CREATE_CONTACT" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_STATUS" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CREATE_DATE"  VARCHAR2(32 BYTE) ,
  "C_LIMIT_CURRENCY" VARCHAR2(32 BYTE) , 
  "C_LIMIT_AMOUNT" VARCHAR2(32 BYTE) , 
  "C_LIMIT_RATE" VARCHAR2(32 BYTE) , 
  "C_LIMIT_UNIT" VARCHAR2(32 BYTE) , 
  "C_LIMIT_COMMENT" VARCHAR2(32 BYTE) , 
  "C_LIMIT_VALID_TO" DATE,
  "C_TEMP_CURRENCY" VARCHAR2(32 BYTE) , 
  "C_TEMP_AMOUNT" VARCHAR2(32 BYTE) , 
  "C_TEMP_RATE" VARCHAR2(32 BYTE) , 
  "C_TEMP_UNIT" VARCHAR2(32 BYTE) , 
  "C_TEMP_COMMENT" VARCHAR2(32 BYTE) , 
  "C_TEMP_VALID_TO" DATE,
  "C_CUSTOM_CLASS" VARCHAR2(32 BYTE),  
  "C_CUSTOM_GRADE" VARCHAR2(32 BYTE),
  "C_CORP_PAY_DAYS" VARCHAR2(10 BYTE),
  "C_GRADE_CHANGETO" VARCHAR2(32 BYTE),
  "C_PAY_DAYS_CHANGETO" VARCHAR2(10 BYTE),
  "C_PIPE_CLASS" VARCHAR2(32 BYTE) , 
  "C_PIPE_ATTR" VARCHAR2(100 BYTE) , 
  "C_PIPE_RANK" VARCHAR2(100 BYTE), 
  "C_YEAR_BEFORE_TURNOVER" VARCHAR2(32 BYTE) ,
  "C_YEAR_CURRENT_TURNOVER" VARCHAR2(32 BYTE) ,
  "C_LIMIT_CURRENCY_OLD" VARCHAR2(32 BYTE) ,
  "C_LIMIT_AMOUNT_OLD" VARCHAR2(32 BYTE) ,
  "C_LIMIT_RATE_OLD" VARCHAR2(32 BYTE) ,
  "C_TEMP_CURRENCY_OLD" VARCHAR2(32 BYTE) ,
  "C_TEMP_AMOUNT_OLD" VARCHAR2(32 BYTE) ,
  "C_TEMP_RATE_OLD" VARCHAR2(32 BYTE) ,
  "C_PLEDGE" VARCHAR2(32 BYTE) ,
  "C_COMMENT" VARCHAR2(32 BYTE) ,
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CUSTOM_CREDIT_ADJUSTMENT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CREDIT_ADJUSTMENT_CODE" IS '申请编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CUSTOM_CODE" IS '客户编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CUSTOM_FULL_NAME" IS '客户名称';

  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."APPLIER_ID" IS '申请人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."APPLIER_POS_ID" IS '申请人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."APPLIER_ORG_ID" IS '申请人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CREATE_CONTACT" IS '申请人联系方式';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_STATUS" IS '状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CREATE_DATE" IS '创建日期';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_CURRENCY" IS '信用额度-常规-币种';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_AMOUNT" IS '信用额度-常规-额度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_RATE" IS '信用额度-常规-汇率';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_UNIT" IS '信用额度-常规-业务实体';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_COMMENT" IS '信用额度-常规-说明';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_VALID_TO" IS '信用额度-常规-有效期至';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_CURRENCY" IS '信用额度-临时-币种';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_AMOUNT" IS '信用额度-临时-额度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_RATE" IS '信用额度-临时-汇率';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_UNIT" IS '信用额度-临时-业务实体';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_COMMENT" IS '信用额度-临时-说明';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_VALID_TO" IS '信用额度-临时-有效期至';
 
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CUSTOM_CLASS" IS '客户类别';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CUSTOM_GRADE" IS '客户等级';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CORP_PAY_DAYS" IS '账期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_PIPE_CLASS" IS '渠道类别';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_PIPE_ATTR" IS '渠道属性';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_PIPE_RANK" IS '签约经销商等级';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_GRADE_CHANGETO" IS '等级调整至';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_PAY_DAYS_CHANGETO" IS '账期调整至';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_CURRENCY_OLD" IS '原信用额度-常规-币种';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_AMOUNT_OLD" IS '原信用额度-常规-额度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_LIMIT_RATE_OLD" IS '原信用额度-常规-汇率';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_CURRENCY_OLD" IS '原信用额度-临时-币种';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_AMOUNT_OLD" IS '原信用额度-临时-额度';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_TEMP_RATE_OLD" IS '原信用额度-临时-汇率';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_YEAR_BEFORE_TURNOVER" IS '去年营业额';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_YEAR_CURRENT_TURNOVER" IS '今年营业额';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_PLEDGE" IS '抵押物';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_COMMENT" IS '备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_CREDIT_ADJUSTMENT"."DT_UPDATED_AT" IS '更新时间';
  
  
  
  
  
  --客户合并
CREATE TABLE "CRM_T_CUSTOM_MERGE" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_MERGE_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_CODE_FRM" VARCHAR2(32 BYTE),
  "C_CUSTOM_NAME_FRM" VARCHAR2(200 BYTE),
  "C_CUSTOM_CODE_TO" VARCHAR2(32 BYTE),
  "C_CUSTOM_NAME_TO" VARCHAR2(200 BYTE),
  "C_MERGE_REASON" VARCHAR2(32 BYTE),
  "C_MERGE_STATUS" VARCHAR2(32 BYTE),
  "C_MERGE_DATE" VARCHAR2(32 BYTE),
  "C_MERGE_ERP_FLG" VARCHAR2(32 BYTE),
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_MERGE" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_MERGE_CODE" IS '合并编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CUSTOM_CODE_FRM" IS '重复客户编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CUSTOM_NAME_FRM" IS '重复客户名称';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CUSTOM_CODE_TO" IS '合并至客户编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CUSTOM_NAME_TO" IS '合并至客户名称';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_MERGE_REASON" IS '合并原因';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_MERGE_STATUS" IS '状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_MERGE_DATE" IS '合并日期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_MERGE_ERP_FLG" IS 'ERP已合并';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."APPLIER_ID" IS '申请人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."APPLIER_POS_ID" IS '申请人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."APPLIER_ORG_ID" IS '申请人组织';
  
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_MERGE"."DT_UPDATED_AT" IS '更新时间';
  
--竞争对手提报
CREATE TABLE "CRM_T_CUSTOM_COMPETITOR_REPORT" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_REPORT_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_CODE_TEAM_IN" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_NAME_TEAM_IN" VARCHAR2(200 BYTE) ,
  "C_STATUS" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_REOPRT_DATE" VARCHAR2(20 BYTE),
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_COMMENT" VARCHAR2(200 BYTE) ,
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CUSTOM_COMPETITOR_REPORT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_REPORT_CODE" IS '报告编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_CUSTOM_CODE_TEAM_IN" IS '内部公司编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_CUSTOM_NAME_TEAM_IN" IS '内部公司名';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_STATUS" IS '报告状态';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_REOPRT_DATE" IS '报告日期';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_COMMENT" IS '备注';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."DT_UPDATED_AT" IS '更新时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."APPLIER_ID" IS '申请人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."APPLIER_POS_ID" IS '申请人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_REPORT"."APPLIER_ORG_ID" IS '申请人组织';
  
  
--竞争对手-业绩
CREATE TABLE "CRM_T_CUSTOM_COMPETITOR_ACHI" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_REPORT_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_CUSTOM_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_COMPETITOR_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_COMPETITOR_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
  "C_COMP_YEAR_RESULT" VARCHAR2(300 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CUSTOM_COMPETITOR_ACHI" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_REPORT_ID" IS '报告编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_CUSTOM_CODE" IS '客户编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_COMPETITOR_CODE" IS '竞争对手编号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_COMPETITOR_NAME" IS '竞争对手名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_COMP_YEAR_RESULT" IS '今年完成业绩';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMPETITOR_ACHI"."DT_UPDATED_AT" IS '更新时间';
  
  --竞争对手-业绩分解-产品分解
CREATE TABLE "CRM_T_CUSTOM_COMP_ACHI_PRODCUT" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_REPORT_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_ACHI_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_PRODUCT_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_COMP_YEAR_BEFORE_RESULT" VARCHAR2(300 BYTE),
  "C_COMMENT" VARCHAR2(300 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_COMP_ACHI_PRODCUT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_REPORT_PID" IS '竞争对手提报ID';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_ACHI_PID" IS '业绩信息主键';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_PRODUCT_CODE" IS '产品名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_COMP_YEAR_BEFORE_RESULT" IS '去年完成业绩';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_COMMENT" IS '备注';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_PRODCUT"."DT_UPDATED_AT" IS '更新时间';
  
  --竞争对手-业绩分解-行业分解
CREATE TABLE "CRM_T_CUSTOM_COMP_ACHI_BIZ" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_REPORT_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_ACHI_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_INDUSTRY_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_COMP_YEAR_BEFORE_RESULT" VARCHAR2(300 BYTE),
  "C_COMMENT" VARCHAR2(300 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_COMP_ACHI_BIZ" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_REPORT_PID" IS '竞争对手提报ID';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_ACHI_PID" IS '业绩信息主键';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_INDUSTRY_CODE" IS '行业名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_COMP_YEAR_BEFORE_RESULT" IS '去年完成业绩';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_COMMENT" IS '备注';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_BIZ"."DT_UPDATED_AT" IS '更新时间';
  
  --竞争对手-业绩分解-对手产品及建议
CREATE TABLE "CRM_T_CUSTOM_COMP_ACHI_DEEP" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,  
  "C_REPORT_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_ACHI_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_PRODUCT_CODE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
  "C_COMP_PRUDUCT_SET" VARCHAR2(300 BYTE),
  "C_COMP_PRUDUCT_USP" VARCHAR2(300 BYTE),
  "C_COMP_PRUDUCT_EQU" VARCHAR2(300 BYTE),
  "C_COMP_PRUDUCT_SUGG" VARCHAR2(300 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_COMP_ACHI_DEEP" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_REPORT_PID" IS '竞争对手提报ID';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_ACHI_PID" IS '业绩信息主键';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_PRODUCT_CODE" IS '产品名称';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_COMP_PRUDUCT_SET" IS '竞争对手主推产品系列';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_COMP_PRUDUCT_USP" IS '竞争对手产品卖点';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_COMP_PRUDUCT_EQU" IS '对应科士达产品系列';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_COMP_PRUDUCT_SUGG" IS '科士达对应产品改善建议';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_COMP_ACHI_DEEP"."DT_UPDATED_AT" IS '更新时间';
  
  
  
  --客户信息变更储存表

CREATE TABLE "CRM_T_CUSTOM_INFO_UPDATE" 
  (  "C_PID" VARCHAR2(32) NOT NULL ENABLE,
  "C_CUSTOM_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_ADDRESS_ID" VARCHAR2(32 BYTE), 
  "APPLIER_ID" VARCHAR2(32 BYTE),
  "APPLIER_POS_ID" VARCHAR2(32 BYTE),
  "APPLIER_ORG_ID" VARCHAR2(32 BYTE),
  "C_CREATE_DATE"  VARCHAR2(32 BYTE) ,
  "C_STATUS"  VARCHAR2(32 BYTE) ,
  "C_CUSTOM_FULL_NAME" VARCHAR2(300 BYTE) ,
  "C_CUSTOM_ALIAS_NAME" VARCHAR2(300 BYTE),
  "C_CUSTOM_WEB_ADDRESS" VARCHAR2(300 BYTE),
  "C_CUSTOM_OEM" VARCHAR2(300 BYTE),
  "C_CUSTOM_AREA" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_AREA_SUB1" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_AREA_SUB2" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_AREA_SUB3" VARCHAR2(32 BYTE) ,
  "C_CUSTOM_INCOME_SCALE" VARCHAR2(32 BYTE),
  "C_CUSTOM_CATEGORY" VARCHAR2(32 BYTE),
  "C_CUSTOM_CATEGORY_SUB" VARCHAR2(32 BYTE),
  "C_CUSTOM_PROFILE" VARCHAR2(300 BYTE),
  "C_CORP_REPRESENTATIVE" VARCHAR2(100 BYTE) ,
  "C_CORP_TRN" VARCHAR2(20 BYTE),
  "C_CORP_INVOICE_NAME" VARCHAR2(100 BYTE), 
  "C_CORP_INVOICE_COMMENT" VARCHAR2(100 BYTE),
  "C_REG_ADDRESS" VARCHAR2(300 BYTE),
  "C_TEMP_FULL_NAME" VARCHAR2(300 BYTE),
  "C_TEMP_ALIAS_NAME" VARCHAR2(300 BYTE),
  "C_TEMP_WEB_ADDRESS" VARCHAR2(300 BYTE),
  "C_TEMP_OEM" VARCHAR2(300 BYTE),
  "C_TEMP_AREA" VARCHAR2(32 BYTE),
  "C_TEMP_AREA_SUB1" VARCHAR2(32 BYTE),
  "C_TEMP_AREA_SUB2" VARCHAR2(32 BYTE),
  "C_TEMP_AREA_SUB3" VARCHAR2(32 BYTE),
  "C_TEMP_INCOME_SCALE" VARCHAR2(32 BYTE),
  "C_TEMP_CATEGORY" VARCHAR2(32 BYTE),
  "C_TEMP_CATEGORY_SUB" VARCHAR2(32 BYTE),
  "C_TEMP_PROFILE" VARCHAR2(300 BYTE),
  "C_TEMP_REPRESENTATIVE" VARCHAR2(100 BYTE),
  "C_TEMP_TRN" VARCHAR2(20 BYTE),
  "C_TEMP_INVOICE_NAME" VARCHAR2(100 BYTE),
  "C_TEMP_INVOICE_COMMENT" VARCHAR2(100 BYTE),
  "C_TEMP_REG_ADDRESS" VARCHAR2(300 BYTE),
  "C_CORP_ORDINARY_FLG" VARCHAR2(300 BYTE),
  "C_ACCOUNT_ADDRESS" VARCHAR2(300 BYTE),
  "C_ACCOUNT_BANK" VARCHAR2(300 BYTE),
  "C_ACCOUNT_TEL" VARCHAR2(300 BYTE),
  "C_ACCOUNT_NO" VARCHAR2(300 BYTE),
  "C_TEMP_ORDINARY_FLG" VARCHAR2(300 BYTE),
  "C_TEMP_ACCOUNT_ADDRESS" VARCHAR2(300 BYTE),
  "C_TEMP_ACCOUNT_BANK" VARCHAR2(300 BYTE),
  "C_TEMP_ACCOUNT_TEL" VARCHAR2(300 BYTE),
  "C_TEMP_ACCOUNT_NO" VARCHAR2(300 BYTE),
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_CUSTOM_INFO_UPDATE" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_PID" IS '主键自增';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_ID" IS '客户ID';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_ADDRESS_ID" IS '地址ID';

COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."APPLIER_ID" IS '申请人ID';
COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."APPLIER_POS_ID" IS '申请人岗位';
COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."APPLIER_ORG_ID" IS '申请人组织';
COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CREATE_DATE" IS '创建日期';
COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_STATUS" IS '状态';

  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_FULL_NAME" IS '客户全称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_ALIAS_NAME" IS '客户别名';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_WEB_ADDRESS" IS '公司网址';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_OEM" IS 'OEM 品牌';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_AREA" IS '所属区域 国家';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_AREA_SUB1" IS '所属区域 省';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_AREA_SUB2" IS '所属区域 市';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_AREA_SUB3" IS '所属区域 区县';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_INCOME_SCALE" IS '收入规模';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_CATEGORY" IS '客户行业 大类';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_CATEGORY_SUB" IS '客户行业 小类';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CUSTOM_PROFILE" IS '客户概况';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CORP_REPRESENTATIVE" IS '法定代表人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CORP_TRN" IS '纳税登记号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CORP_INVOICE_NAME" IS '开票名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CORP_INVOICE_COMMENT" IS '开票注意事项';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_REG_ADDRESS" IS '注册地址';

  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_FULL_NAME" IS '客户全称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_ALIAS_NAME" IS '客户别名';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_WEB_ADDRESS" IS '公司网址';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_OEM" IS 'OEM 品牌';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_AREA" IS '所属区域';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_AREA_SUB1" IS '所属区域 省';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_AREA_SUB2" IS '所属区域 市';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_AREA_SUB3" IS '所属区域 区县';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_INCOME_SCALE" IS '收入规模';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_CATEGORY" IS '客户行业';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_CATEGORY_SUB" IS '客户行业 小类';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_PROFILE" IS '客户概况';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_REPRESENTATIVE" IS '法定代表人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_TRN" IS '纳税登记号';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_INVOICE_NAME" IS '开票名称';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_INVOICE_COMMENT" IS '开票注意事项';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_REG_ADDRESS" IS '注册地址';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CORP_ORDINARY_FLG" IS '一般纳税人资格 ';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_ACCOUNT_ADDRESS" IS '开票地址 ';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_ACCOUNT_BANK" IS '开户行';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_ACCOUNT_TEL" IS '开票电话';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_ACCOUNT_NO" IS '开户账号';
  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_ORDINARY_FLG" IS '一般纳税人资格 ';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_ACCOUNT_ADDRESS" IS '开票地址 ';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_ACCOUNT_BANK" IS '开户行';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_ACCOUNT_TEL" IS '开票电话';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_TEMP_ACCOUNT_NO" IS '开户账号';

  
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_CUSTOM_INFO_UPDATE"."DT_UPDATED_AT" IS '更新时间';
  
