drop table CRM_T_CUSTOM_INFO ;
drop table CRM_T_CUSTOM_REQUIRE_INFO ;
drop table CRM_T_CUSTOM_ADDRESS_INFO ;
drop table CRM_T_CUSTOM_FINANCE_PINFO ;
drop table CRM_T_CUSTOM_ERP_INFO ;
drop table CRM_T_CUSTOM_RELATION ;
drop table CRM_T_CUSTOM_RELA_CONTACT ;
drop table CRM_T_CUSTOM_DISTR_SCOPE ;
drop table CRM_T_CUSTOM_EVENT_INFO ;
drop table CRM_T_CUSTOM_SHARE_INFO ;
drop table CRM_T_CUSTOM_HANDOVER_LIST ;
drop table CRM_T_CUSTOM_HANDOVER_RECEIPT ;
drop table CRM_T_CUSTOM_HANDOVER_PROC ;
drop table CRM_T_CUSTOM_CREDIT_ADJUSTMENT ;
drop table CRM_T_CUSTOM_MERGE ;
drop table CRM_T_CUSTOM_COMPETITOR_REPORT ;
drop table CRM_T_CUSTOM_COMPETITOR_ACHI ;

drop table CRM_T_CUSTOM_COMP_ACHI_DEEP ;
drop table CRM_T_CUSTOM_COMP_ACHI_BIZ;
drop table CRM_T_CUSTOM_COMP_ACHI_PRODCUT;
drop table CRM_T_CUSTOM_INFO_UPDATE;

drop table CRM_T_HO_BUSINESS_OPPORTUNITY;
drop table CRM_T_HO_CONTR_BASIC;
drop table CRM_T_HO_CUSTOM_INFO;
drop table CRM_T_HO_ORDER_HEADER;
drop table CRM_T_HO_QUOTATION_BASIC;