  CREATE TABLE "CRM_T_SUPPORT_TEMPLATE" 
  ("C_PID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
  "C_DOC_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
  "C_DOC_COMMENT" VARCHAR2(100 BYTE), 
  "C_CREATED_BY_ID" VARCHAR2(100 BYTE), 
  "DT_CREATED_AT" DATE, 
  "C_CREATED_POS_ID" VARCHAR2(100 BYTE), 
  "C_CREATED_ORG_ID" VARCHAR2(100 BYTE),
  "C_UPDATED_BY_ID" VARCHAR2(100 BYTE),
  "DT_UPDATED_AT" DATE, 
  CONSTRAINT "PK_CRM_T_SUPPORT_TEMPLATE" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;

  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_PID" IS '文档ID';
 
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_DOC_TYPE" IS '文档目录名称';
 
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_DOC_COMMENT" IS '目录描述';
  
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_CREATED_BY_ID" IS '创建人';
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."DT_CREATED_AT" IS '创建时间';
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_CREATED_POS_ID" IS '创建人岗位';
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_CREATED_ORG_ID" IS '创建人组织';
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."C_UPDATED_BY_ID" IS '更新者';
  COMMENT ON COLUMN "CRM_T_SUPPORT_TEMPLATE"."DT_UPDATED_AT" IS '更新时间';
 
