CREATE TABLE "KCRM"."CRM_T_PRODUCT_CLIENT" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_CLIENT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"C_CLIENT_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"C_CLIENT_MODEL" VARCHAR2(20), 
	"C_CLIENT_BRAND" VARCHAR2(20), 
	"C_CLIENT_REMARK" VARCHAR2(100), 
	"C_PRO_ID" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRO_CLIENT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."PK_PRO_CLIENT" ON "KCRM"."CRM_T_PRODUCT_CLIENT" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CLIENT" ADD CONSTRAINT "PK_PRO_CLIENT" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CLIENT" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CLIENT" MODIFY ("C_CLIENT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CLIENT" MODIFY ("C_CLIENT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CLIENT" MODIFY ("C_PRO_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_PID" IS '客户ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_CLIENT_NAME" IS '客户名称(CRM客户名称)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_CLIENT_CODE" IS '客户编码(CRM客户编码)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_CLIENT_MODEL" IS '客户型号(客户产品型号)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_CLIENT_BRAND" IS '客户品牌';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_CLIENT_REMARK" IS '备注说明';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CLIENT"."C_PRO_ID" IS '产品ID';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRODUCT_CLIENT"  IS '产品客户表';