CREATE TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_DIRECT_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_DIRECT_NAME" VARCHAR2(255), 
	"C_PRO_CATEGORY" VARCHAR2(40) NOT NULL ENABLE, 
	"C_PRO_MODEL" VARCHAR2(40), 
	"C_EFFECTIVE" CHAR(1) NOT NULL ENABLE, 
	"DT_START_TIME" DATE NOT NULL ENABLE, 
	"DT_END_TIME" DATE, 
	"C_COMMENT" VARCHAR2(200), 
	 CONSTRAINT "CATALOG_MATCH_KEY" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."CATALOG_MATCH_KEY" ON "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."UNIQUE_CATELOG_MATCH" ON "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" ("C_DIRECT_ID", "C_PRO_CATEGORY", "C_PRO_MODEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" ADD CONSTRAINT "CATALOG_MATCH_KEY" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" MODIFY ("C_DIRECT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" MODIFY ("C_PRO_CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" MODIFY ("C_EFFECTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH" MODIFY ("DT_START_TIME" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_PID" IS 'id';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_DIRECT_ID" IS '目录ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_DIRECT_NAME" IS '目录名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_PRO_CATEGORY" IS '产品分类';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_PRO_MODEL" IS '产品型号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_EFFECTIVE" IS '有效';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."DT_START_TIME" IS '有效期开始时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."DT_END_TIME" IS '有效期结束时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_CATALOG_MATCH"."C_COMMENT" IS '说明';