CREATE TABLE "KCRM"."CRM_T_ECR" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"DT_EFFECT_TIME" DATE, 
	"C_ECR_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"C_ECR_CHANGE_TYPE" VARCHAR2(100), 
	"C_ECR_CHANGE_REASON" VARCHAR2(100) NOT NULL ENABLE, 
	"C_CREATE_BY" VARCHAR2(32), 
	"DT_CREATE_TIME" DATE, 
	"C_ERGENT" VARCHAR2(10) NOT NULL ENABLE, 
	"C_ECR_CHANGE_CONTENT" VARCHAR2(100) NOT NULL ENABLE, 
	"C_REFER_PID" VARCHAR2(32), 
	"C_STATUS" VARCHAR2(32) NOT NULL ENABLE, 
	"C_ECR_APPLY" VARCHAR2(32) NOT NULL ENABLE, 
	"C_ECN_NUMBER" VARCHAR2(20), 
	"C_PRO_ID" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "N_PID_ECR" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."N_PID_ECR" ON "KCRM"."CRM_T_ECR" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_ECR" ADD CONSTRAINT "N_PID_ECR" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_ECR_CHANGE_REASON" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_ERGENT" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_ECR_CHANGE_CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("DT_CREATE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_ECR_APPLY" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_ECR_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_ECR" MODIFY ("C_PRO_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_PID" IS '工艺 ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."DT_EFFECT_TIME" IS 'ECR最近生效时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ECR_CODE" IS 'ECR变更单号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ECR_CHANGE_TYPE" IS '变更原因类型';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ECR_CHANGE_REASON" IS '变更原因';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_CREATE_BY" IS '创建人';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."DT_CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ERGENT" IS '紧急程度';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ECR_CHANGE_CONTENT" IS '变更内容/项目';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_REFER_PID" IS '参考已有ECR';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_STATUS" IS '状态';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ECR_APPLY" IS '申请人';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_ECN_NUMBER" IS 'ECN单号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_ECR"."C_PRO_ID" IS '产品ID';