CREATE TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_TEST_NAME" VARCHAR2(32), 
	"C_PRO_TEST_DESC" VARCHAR2(200), 
	"C_PRO_TEST_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_MODEL" VARCHAR2(32) NOT NULL ENABLE, 
	"DT_SUB_TIME" DATE,
	"DT_COMPLETE_TIME" DATE, 
	"C_STATUS" VARCHAR2(32), 
	"C_APPLY_DEPARTMENT" VARCHAR2(32) NOT NULL ENABLE, 
	"C_APPLY_PERSON" VARCHAR2(32) NOT NULL ENABLE, 
	"C_AUTH_CODE" VARCHAR2(20), 
	"C_AUTH_RESULT" VARCHAR2(200), 
	"C_PRO_ID" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRO_AUTEST" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."PK_PRO_AUTEST" ON "KCRM"."CRM_T_PRODUCT_AUTEST" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" ADD CONSTRAINT "PK_PRO_AUTEST" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("C_PRO_TEST_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("C_PRO_MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("DT_SUB_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("C_APPLY_DEPARTMENT" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("C_APPLY_PERSON" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_AUTEST" MODIFY ("C_PRO_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_PID" IS '认证测试ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_PRO_TEST_NAME" IS '认证测试名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_PRO_TEST_DESC" IS '认证测试事项或需求说明';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_PRO_TEST_TYPE" IS '认证类型';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_PRO_MODEL" IS '产品型号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."DT_SUB_TIME" IS '提交时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."DT_COMPLETE_TIME" IS '需求完成时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_STATUS" IS '状态(新增/已提交/已完成/已退回)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_APPLY_DEPARTMENT" IS '申请部门';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_APPLY_PERSON" IS '申请人';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_AUTH_CODE" IS '认证编号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_AUTH_RESULT" IS '认证结果';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_AUTEST"."C_PRO_ID" IS '产品ID';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRODUCT_AUTEST"  IS '产品认证与测试';