CREATE TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_LAYER_COMPARE_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"DT_START_DATE" DATE NOT NULL ENABLE, 
	"DT_END_DATE" DATE, 
	"C_ORGANIZATION" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRICE_COMP_DESC" VARCHAR2(200), 
	 CONSTRAINT "PK_PRICE_LAYER_COMP_HEADER" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."UNIQUE_ORIGA" ON "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" ("C_ORGANIZATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."PK_PRICE_LAYER_COMP_HEADER" ON "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" ADD CONSTRAINT "PK_PRICE_LAYER_COMP_HEADER" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" MODIFY ("C_LAYER_COMPARE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" MODIFY ("DT_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER" MODIFY ("C_ORGANIZATION" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"."C_PID" IS '层级对照表ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"."C_LAYER_COMPARE_NAME" IS '层级对照表名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"."DT_START_DATE" IS '有效期开始时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"."DT_END_DATE" IS '有效期结束时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"."C_ORGANIZATION" IS '组织';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"."C_PRICE_COMP_DESC" IS '说明';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRICE_LAYER_COMHEADER"  IS '层级对照表头信息';