CREATE TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_LAYER_LINE_NAME" VARCHAR2(32) NOT NULL ENABLE, 
	"DT_START_DATE" DATE NOT NULL ENABLE, 
	"DT_END_DATE" DATE, 
	"N_DISCOUNT_RATE" NUMBER NOT NULL ENABLE, 
	"C_HEADER_ID" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "PK_LAYER_COMP_LINE_PK" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE, 
	 CONSTRAINT "LAYER_LINE_U1" UNIQUE ("C_HEADER_ID", "C_LAYER_LINE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."PK_LAYER_COMP_LINE_PK" ON "KCRM"."CRM_T_PRICE_LAYER_COMLINE" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."LAYER_LINE_U1" ON "KCRM"."CRM_T_PRICE_LAYER_COMLINE" ("C_HEADER_ID", "C_LAYER_LINE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" ADD CONSTRAINT "LAYER_LINE_U1" UNIQUE ("C_HEADER_ID", "C_LAYER_LINE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" ADD CONSTRAINT "PK_LAYER_COMP_LINE_PK" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" MODIFY ("C_LAYER_LINE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" MODIFY ("DT_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" MODIFY ("N_DISCOUNT_RATE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE" MODIFY ("C_HEADER_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMLINE"."C_PID" IS '行ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMLINE"."C_LAYER_LINE_NAME" IS '层级名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMLINE"."DT_START_DATE" IS '有效期结束时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMLINE"."DT_END_DATE" IS '有效期结束时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMLINE"."N_DISCOUNT_RATE" IS '默认折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LAYER_COMLINE"."C_HEADER_ID" IS '头ID';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRICE_LAYER_COMLINE"  IS '层级价格对照表行信息';