CREATE TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_DEMAND_CODE" VARCHAR2(12) NOT NULL ENABLE, 
	"C_DEMAND_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"C_CLIENT_CODE" VARCHAR2(32) NOT NULL ENABLE, 
	"C_CLIENT_ADDRESS" VARCHAR2(32) NOT NULL ENABLE, 
	"C_CLIENT_CONTRACT" VARCHAR2(32), 
	"DT_HOPEDELIVER_DATE" DATE NOT NULL ENABLE, 
	"C_DEMANT_CATEGORY" VARCHAR2(32) NOT NULL ENABLE, 
	"N_DEMANT_NUMBER" NUMBER NOT NULL ENABLE, 
	"C_PREPARE_BEFORE" VARCHAR2(12) DEFAULT 0 NOT NULL ENABLE, 
	"C_DEMAND_DEPARTMENT" VARCHAR2(32) NOT NULL ENABLE, 
	"C_DEMAND_PERSON" VARCHAR2(32) NOT NULL ENABLE, 
	"C_CONTRACT_TEL" VARCHAR2(16), 
	"C_DEMAND_STATUS" VARCHAR2(12) NOT NULL ENABLE, 
	"C_SPEC_REQUIRE_LIST" VARCHAR2(200) NOT NULL ENABLE, 
	"C_CLIENT_DOC" VARCHAR2(200), 
	"C_PRO_ID" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRO_DEMAND" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."PK_PRO_DEMAND" ON "KCRM"."CRM_T_PRODUCT_DEMAND" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" ADD CONSTRAINT "PK_PRO_DEMAND" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_DEMAND_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_DEMAND_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_CLIENT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_CLIENT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("DT_HOPEDELIVER_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_DEMANT_CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("N_DEMANT_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_PREPARE_BEFORE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_DEMAND_DEPARTMENT" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_DEMAND_PERSON" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_DEMAND_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_SPEC_REQUIRE_LIST" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_DEMAND" MODIFY ("C_PRO_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_PID" IS '需求单ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_DEMAND_CODE" IS '需求单编号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_DEMAND_NAME" IS '需求单名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_CLIENT_CODE" IS '客户编码';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_CLIENT_ADDRESS" IS '客户所在地  地址PID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_CLIENT_CONTRACT" IS '客户PO/合同';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."DT_HOPEDELIVER_DATE" IS '期望交货日期';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_DEMANT_CATEGORY" IS '需求种类(订单
/样机)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."N_DEMANT_NUMBER" IS '需求数量';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_PREPARE_BEFORE" IS '是否提前备料';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_DEMAND_DEPARTMENT" IS '需求部门';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_DEMAND_PERSON" IS '需求人员';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_CONTRACT_TEL" IS ' 联系电话';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_DEMAND_STATUS" IS '需求状态(新增/已提交
/已入库)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_SPEC_REQUIRE_LIST" IS '特殊产品规格需求清单';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_CLIENT_DOC" IS '客户资料';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_DEMAND"."C_PRO_ID" IS ' 产品ID';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRODUCT_DEMAND"  IS '产品需求单';