CREATE TABLE "KCRM"."CRM_T_PRODUCT_SERIAL" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_TYPE" CHAR(1) NOT NULL ENABLE, 
	"C_PRO_DATE" VARCHAR2(8) NOT NULL ENABLE, 
	"N_COUNT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "KP_PRO_SERIAL" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."KP_PRO_SERIAL" ON "KCRM"."CRM_T_PRODUCT_SERIAL" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."UNK_PRO_SERIAL" ON "KCRM"."CRM_T_PRODUCT_SERIAL" ("C_PRO_TYPE", "C_PRO_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_SERIAL" ADD CONSTRAINT "KP_PRO_SERIAL" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_SERIAL" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_SERIAL" MODIFY ("C_PRO_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_SERIAL" MODIFY ("C_PRO_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_SERIAL" MODIFY ("N_COUNT" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_SERIAL"."C_PID" IS '主键';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_SERIAL"."C_PRO_TYPE" IS '标准品（S，非标品（N），服务类（F），商务类（B），外购品（P）';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_SERIAL"."C_PRO_DATE" IS '产生日期（yyyyMMdd 8位数字）';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_SERIAL"."N_COUNT" IS '计数（1-999）';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRODUCT_SERIAL"  IS '预定义物料号 序列号表';