CREATE TABLE "KCRM"."CRM_T_PRODUCT_BASIC" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_CODE" VARCHAR2(12) NOT NULL ENABLE, 
	"C_PRO_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"C_PRO_ENAME" VARCHAR2(30), 
	"C_PRO_DESC" VARCHAR2(300), 
	"C_MATER_CODE" VARCHAR2(12), 
	"C_VMATER_CODE" VARCHAR2(12), 
	"C_PRO_MODEL" VARCHAR2(10), 
	"C_FATHER_PRO" VARCHAR2(32), 
	"C_PRO_PUBLISH_STATUS" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_PRICE_STATUS" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_SALE_STATUS" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_ROHS_STATUS" CHAR(1), 
	"C_PRO_ORG_ID" VARCHAR2(10), 
	"C_UNIT" VARCHAR2(4), 
	"C_BRAND" VARCHAR2(12), 
	"C_PRO_LINE_ID" VARCHAR2(20), 
	"C_PRO_ERP_CATEGORY" VARCHAR2(12), 
	"C_PRO_CRM_CATEGORY" VARCHAR2(12) NOT NULL ENABLE, 
	"C_SALE_TYPE" VARCHAR2(12), 
	"C_SALE_STATUS" VARCHAR2(12), 
	"C_CLIENT_CATEGORY" VARCHAR2(12), 
	"C_CLIENT_CODE" VARCHAR2(12), 
	"C_SPECIAL_USE" CHAR(1) DEFAULT 0 NOT NULL ENABLE, 
	"C_SUPPLY_CHAIN" VARCHAR2(10), 
	"N_GROSS_WEIGHT" NUMBER, 
	"N_NET_WEIGHT" NUMBER, 
	"N_PRO_LENGTH" NUMBER, 
	"N_PRO_WIDTH" NUMBER, 
	"N_PRO_HEIGHT" NUMBER, 
	"N_PRO_WRAP_LENGTH" NUMBER, 
	"N_PRO_WRAP_WIDTH" NUMBER, 
	"N_PRO_WRAP_HEIGHT" NUMBER, 
	"N_CABINET_20FLAT" NUMBER, 
	"N_CABINET_20WIGHT" NUMBER, 
	"N_CABINET_40FLAT" NUMBER, 
	"N_CABINET_40HIGHT" NUMBER, 
	"C_CUSTOMS_CODE" VARCHAR2(12), 
	"C_DEMAND_CODE" VARCHAR2(11), 
	"N_CLIENT_ID" NUMBER, 
	"C_PRO_POWCAP" VARCHAR2(20), 
	"CREATED_BY_ID"        VARCHAR2(32),
	"CREATED_AT"           DATE default sysdate,
	"CREATED_POS_ID"       VARCHAR2(32),
	"CREATED_ORG_ID"       VARCHAR2(32),
	"UPDATED_BY_ID"        VARCHAR2(32),
	"UPDATED_AT"           DATE default sysdate,
	 CONSTRAINT "C_PID" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."I_PRO_CODE" ON "KCRM"."CRM_T_PRODUCT_BASIC" ("C_PRO_CODE", "C_PRO_ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."C_PID" ON "KCRM"."CRM_T_PRODUCT_BASIC" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" ADD CONSTRAINT "C_PID" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PRO_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PRO_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PRO_PUBLISH_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PRO_PRICE_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PRO_SALE_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_PRO_CRM_CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRODUCT_BASIC" MODIFY ("C_SPECIAL_USE" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PID" IS 'primary key';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_CODE" IS '产品编码';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_NAME" IS '产品名称';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_ENAME" IS '英文名';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_DESC" IS '产品描述';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_MATER_CODE" IS '物料号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_VMATER_CODE" IS '预定义物料号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_MODEL" IS '产品型号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_FATHER_PRO" IS '父产品';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_PUBLISH_STATUS" IS '产品发布状态';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_PRICE_STATUS" IS '产品订价状态';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_SALE_STATUS" IS '产品转销状态';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_ROHS_STATUS" IS '是否RoHS';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_ORG_ID" IS '组织ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_UNIT" IS '单位';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_BRAND" IS '品牌';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_LINE_ID" IS '产品线ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_ERP_CATEGORY" IS 'ERP产品类别';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_CRM_CATEGORY" IS 'CRM产品类别';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_SALE_TYPE" IS '销售类型';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_SALE_STATUS" IS '销售状态';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_CLIENT_CATEGORY" IS '客户型号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_CLIENT_CODE" IS '供应商';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_SPECIAL_USE" IS '是否专用料';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_SUPPLY_CHAIN" IS '供应链ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_GROSS_WEIGHT" IS '毛重';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_NET_WEIGHT" IS '净重';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_PRO_LENGTH" IS '产品长(cm)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_PRO_WIDTH" IS '产品宽(cm)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_PRO_HEIGHT" IS '产品高(cm)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_PRO_WRAP_LENGTH" IS '包装长(cm)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_PRO_WRAP_WIDTH" IS '包装宽(cm)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_PRO_WRAP_HEIGHT" IS '包装高(cm)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_CABINET_20FLAT" IS '装柜数量(20尺平柜)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_CABINET_20WIGHT" IS '装柜数量(20尺超重柜)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_CABINET_40FLAT" IS '装柜数量(40尺普通柜)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_CABINET_40HIGHT" IS '装柜数量(40尺高柜)';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_CUSTOMS_CODE" IS '海关料号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_DEMAND_CODE" IS '需求单编号';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."N_CLIENT_ID" IS '客户ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRODUCT_BASIC"."C_PRO_POWCAP" IS '功率或容量';
   
   --extend the length for interface data imported
   alter table KCRM.CRM_T_PRODUCT_BASIC modify (C_PRO_CODE VARCHAR2(64));
   alter table KCRM.CRM_T_PRODUCT_BASIC modify (C_PRO_NAME VARCHAR2(128));
   alter table KCRM.CRM_T_PRODUCT_BASIC modify (C_BRAND VARCHAR2(128));
   alter table KCRM.CRM_T_PRODUCT_BASIC modify (C_PRO_MODEL VARCHAR2(128));
   
   --add a optional column for RETURN_ABLE_FLAG.
   alter table KCRM.CRM_T_PRODUCT_BASIC add opt_txt1 varchar2(128);
   
   --add a optional column for INVENTORY_ITEM_FLAG .
   alter table KCRM.CRM_T_PRODUCT_BASIC add opt_txt2 varchar2(128);
   
   --new added for PDM material code.
   alter table KCRM.CRM_T_PRODUCT_BASIC add opt_txt3 varchar2(128);
   