CREATE TABLE "KCRM"."CRM_T_PRICE_LINE" 
   (	"C_PID" VARCHAR2(32) NOT NULL ENABLE, 
	"C_PRO_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"N_PRO_COST" NUMBER, 
	"N_CATALOG_PRICE" NUMBER NOT NULL ENABLE, 
	"N_CATALOG_RATE" NUMBER, 
	"DT_START_DATE" DATE NOT NULL ENABLE, 
	"DT_END_DATE" DATE, 
	"C_PRICE_HEAD_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"N_LAYER1_PRICE" NUMBER, 
	"N_LAYER1_DISCOUNT" NUMBER, 
	"N_LAYER1_NUMBER" NUMBER, 
	"N_LAYER2_PRICE" NUMBER, 
	"N_LAYER2_DISCOUNT" NUMBER, 
	"N_LAYER2_NUMBER" NUMBER, 
	"N_LAYER3_PRICE" NUMBER, 
	"N_LAYER3_DISCOUNT" NUMBER, 
	"N_LAYER3_NUMBER" NUMBER, 
	"N_LAYER4_PRICE" NUMBER, 
	"N_LAYER4_DISCOUNT" NUMBER, 
	"N_LAYER4_NUMBER" NUMBER, 
	"N_LAYER5_PRICE" NUMBER, 
	"N_LAYER5_DISCOUNT" NUMBER, 
	"N_LAYER5_NUMBER" NUMBER, 
	"N_LAYER6_PRICE" NUMBER, 
	"N_LAYER6_DISCOUNT" NUMBER, 
	"N_LAYER6_NUMBER" NUMBER, 
	 CONSTRAINT "PK_PRICE_LINE" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."PK_PRICE_LINE" ON "KCRM"."CRM_T_PRICE_LINE" ("C_PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  CREATE UNIQUE INDEX "KCRM"."UNIQUE_PRICE_LINE" ON "KCRM"."CRM_T_PRICE_LINE" ("C_PRO_ID", "C_PRICE_HEAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM" ;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LINE" ADD CONSTRAINT "PK_PRICE_LINE" PRIMARY KEY ("C_PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_CRM"  ENABLE;
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LINE" MODIFY ("C_PID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LINE" MODIFY ("C_PRO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LINE" MODIFY ("N_CATALOG_PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LINE" MODIFY ("DT_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "KCRM"."CRM_T_PRICE_LINE" MODIFY ("C_PRICE_HEAD_ID" NOT NULL ENABLE);
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."C_PID" IS '价格行表ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."C_PRO_ID" IS '产品ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_PRO_COST" IS '产品成本';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_CATALOG_PRICE" IS '目录价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_CATALOG_RATE" IS '毛利率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."DT_START_DATE" IS '有效期结束时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."DT_END_DATE" IS '有效期结束时间';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."C_PRICE_HEAD_ID" IS '价格头表ID';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER1_PRICE" IS '层一价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER1_DISCOUNT" IS '层一价折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER1_NUMBER" IS '层一数量级';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER2_PRICE" IS '层二价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER2_DISCOUNT" IS '层二价折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER2_NUMBER" IS '层二数量级';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER3_PRICE" IS '层三价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER3_DISCOUNT" IS '层三价折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER3_NUMBER" IS '层三数量级';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER4_PRICE" IS '层四价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER4_DISCOUNT" IS '层四价折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER4_NUMBER" IS '层四数量级';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER5_PRICE" IS '层五价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER5_DISCOUNT" IS '层五价折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER5_NUMBER" IS '层五数量级';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER6_PRICE" IS '层六价格';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER6_DISCOUNT" IS '层六价折扣率';
 
   COMMENT ON COLUMN "KCRM"."CRM_T_PRICE_LINE"."N_LAYER6_NUMBER" IS '层六数量级';
 
   COMMENT ON TABLE "KCRM"."CRM_T_PRICE_LINE"  IS '价格表行项目';